# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.findings_summary_dto import FindingsSummaryDto

class TestFindingsSummaryDto(unittest.TestCase):
    """FindingsSummaryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindingsSummaryDto:
        """Test FindingsSummaryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindingsSummaryDto`
        """
        model = FindingsSummaryDto()
        if include_optional:
            return FindingsSummaryDto(
                total_resolved_findings = 156,
                old_critical_high_findings = 3,
                unacknowledged_critical_high_findings = 7
            )
        else:
            return FindingsSummaryDto(
                total_resolved_findings = 156,
                old_critical_high_findings = 3,
                unacknowledged_critical_high_findings = 7,
        )
        """

    def testFindingsSummaryDto(self):
        """Test FindingsSummaryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
