# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.containers_api import ContainersApi


class TestContainersApi(unittest.TestCase):
    """ContainersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContainersApi()

    def tearDown(self) -> None:
        pass

    def test_assign_container_to_business_units(self) -> None:
        """Test case for assign_container_to_business_units

        Assign Container to Business Units
        """
        pass

    def test_create_custom_property_container(self) -> None:
        """Test case for create_custom_property_container

        Create Custom Property
        """
        pass

    def test_create_note_container(self) -> None:
        """Test case for create_note_container

        Create Note
        """
        pass

    def test_delete_custom_property_container(self) -> None:
        """Test case for delete_custom_property_container

        Delete Custom Property
        """
        pass

    def test_delete_note_container(self) -> None:
        """Test case for delete_note_container

        Delete Note
        """
        pass

    def test_get_asset_container_changelog(self) -> None:
        """Test case for get_asset_container_changelog

        Get Container Changelog
        """
        pass

    def test_get_asset_container_details(self) -> None:
        """Test case for get_asset_container_details

        Get Container
        """
        pass

    def test_get_asset_container_notes(self) -> None:
        """Test case for get_asset_container_notes

        List Notes
        """
        pass

    def test_get_custom_properties_container(self) -> None:
        """Test case for get_custom_properties_container

        List Custom Properties
        """
        pass

    def test_get_list_asset_container(self) -> None:
        """Test case for get_list_asset_container

        List Containers
        """
        pass

    def test_unassign_container_from_business_units(self) -> None:
        """Test case for unassign_container_from_business_units

        Unassign Container from Business Units
        """
        pass

    def test_update_asset_container_status(self) -> None:
        """Test case for update_asset_container_status

        Update Status
        """
        pass

    def test_update_custom_property_container(self) -> None:
        """Test case for update_custom_property_container

        Update Custom Property
        """
        pass

    def test_update_note_container(self) -> None:
        """Test case for update_note_container

        Update Note
        """
        pass


if __name__ == '__main__':
    unittest.main()
