# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.whois_data_object import WhoisDataObject

class TestWhoisDataObject(unittest.TestCase):
    """WhoisDataObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhoisDataObject:
        """Test WhoisDataObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhoisDataObject`
        """
        model = WhoisDataObject()
        if include_optional:
            return WhoisDataObject(
                org = 'ACME Corp',
                city = 'Singapore',
                name = 'John Doe',
                state = 'Singapore',
                dnssec = 'unsigned',
                emails = None,
                status = None,
                address = 'Singapore 123456',
                country = 'Singapore',
                zipcode = '123456',
                registrar = 'GoDaddy.com, LLC',
                domain_name = 'example.com',
                name_servers = None,
                referral_url = '',
                whois_server = 'whois.godaddy.com',
                creation_date = '1989-07-15T04:00:00',
                expiration_date = '2030-07-15T04:00:00'
            )
        else:
            return WhoisDataObject(
        )
        """

    def testWhoisDataObject(self):
        """Test WhoisDataObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
