# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.client_cloud_storage import ClientCloudStorage

class TestClientCloudStorage(unittest.TestCase):
    """ClientCloudStorage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientCloudStorage:
        """Test ClientCloudStorage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientCloudStorage`
        """
        model = ClientCloudStorage()
        if include_optional:
            return ClientCloudStorage(
                type = 'cloudStorage',
                source = 'module-adversarysight-cloud-integration-aws-s3-buckets',
                status = 'verified',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                name = 'watchtowr-s3-bucket',
                platform = 'awss3',
                url = 'watchtowr-s3-bucket.s3.amazonaws.com',
                business_units = [
                    openapi_client.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ],
                custom_properties = [{"id":10,"key":"Severity","value":"normal","isPreset":false,"modelType":"cloudStorage","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"},{"id":11,"key":"Vulnerability","value":"low risk","isPreset":false,"modelType":"cloudStorage","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"}],
                criticality = 'Medium'
            )
        else:
            return ClientCloudStorage(
                type = 'cloudStorage',
                source = 'module-adversarysight-cloud-integration-aws-s3-buckets',
                status = 'verified',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                name = 'watchtowr-s3-bucket',
                platform = 'awss3',
                url = 'watchtowr-s3-bucket.s3.amazonaws.com',
                business_units = [
                    openapi_client.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ],
                custom_properties = [{"id":10,"key":"Severity","value":"normal","isPreset":false,"modelType":"cloudStorage","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"},{"id":11,"key":"Vulnerability","value":"low risk","isPreset":false,"modelType":"cloudStorage","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"}],
                criticality = 'Medium',
        )
        """

    def testClientCloudStorage(self):
        """Test ClientCloudStorage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
