# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.get_asset_ip_changelog200_response import GetAssetIpChangelog200Response

class TestGetAssetIpChangelog200Response(unittest.TestCase):
    """GetAssetIpChangelog200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetIpChangelog200Response:
        """Test GetAssetIpChangelog200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetIpChangelog200Response`
        """
        model = GetAssetIpChangelog200Response()
        if include_optional:
            return GetAssetIpChangelog200Response(
                data = [{"id":1,"description":"IP created.","type":"Add Asset","properties":{"attributes":{"ip":"10.0.255.170"}},"created_at":"2025-11-25T05:24:59.000Z","caused_by":{"id":1,"name":"watchTowr Platform"}},{"id":2,"description":"IP updated (status).","type":"Asset Status Change","properties":{"old":{"status_name":"pending","status_reason":"Requires verification"},"attributes":{"status_name":"verified","status_reason":"Manually verified via Client API"}},"created_at":"2025-11-25T05:25:00.000Z","caused_by":{"id":54,"name":"John Doe"}}],
                meta = {"pagination":{"count":10,"total":47,"per_page":10,"current_page":1,"total_pages":5,"links":{"next":"url"}}}
            )
        else:
            return GetAssetIpChangelog200Response(
                data = [{"id":1,"description":"IP created.","type":"Add Asset","properties":{"attributes":{"ip":"10.0.255.170"}},"created_at":"2025-11-25T05:24:59.000Z","caused_by":{"id":1,"name":"watchTowr Platform"}},{"id":2,"description":"IP updated (status).","type":"Asset Status Change","properties":{"old":{"status_name":"pending","status_reason":"Requires verification"},"attributes":{"status_name":"verified","status_reason":"Manually verified via Client API"}},"created_at":"2025-11-25T05:25:00.000Z","caused_by":{"id":54,"name":"John Doe"}}],
                meta = {"pagination":{"count":10,"total":47,"per_page":10,"current_page":1,"total_pages":5,"links":{"next":"url"}}},
        )
        """

    def testGetAssetIpChangelog200Response(self):
        """Test GetAssetIpChangelog200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
