# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.dns_record_analysis_api import DNSRecordAnalysisApi


class TestDNSRecordAnalysisApi(unittest.TestCase):
    """DNSRecordAnalysisApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DNSRecordAnalysisApi()

    def tearDown(self) -> None:
        pass

    def test_get_list_dns_records(self) -> None:
        """Test case for get_list_dns_records

        List DNS Records
        """
        pass


if __name__ == '__main__':
    unittest.main()
