# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.adversary_intelligence_api import AdversaryIntelligenceApi


class TestAdversaryIntelligenceApi(unittest.TestCase):
    """AdversaryIntelligenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdversaryIntelligenceApi()

    def tearDown(self) -> None:
        pass

    def test_get_adversary_intelligence_details(self) -> None:
        """Test case for get_adversary_intelligence_details

        Get Adversary Details
        """
        pass

    def test_get_list_adversary_intelligence(self) -> None:
        """Test case for get_list_adversary_intelligence

        List Adversaries
        """
        pass


if __name__ == '__main__':
    unittest.main()
