# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.client_pending_domain_whois_data import ClientPendingDomainWhoisData

class TestClientPendingDomainWhoisData(unittest.TestCase):
    """ClientPendingDomainWhoisData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientPendingDomainWhoisData:
        """Test ClientPendingDomainWhoisData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientPendingDomainWhoisData`
        """
        model = ClientPendingDomainWhoisData()
        if include_optional:
            return ClientPendingDomainWhoisData(
                raw = 'Domain Name: example.com
Registrar: Example Registrar',
                data = {"domainName":"example.com","registrar":"Example Registrar","creationDate":"2020-01-01T00:00:00.000Z"}
            )
        else:
            return ClientPendingDomainWhoisData(
                raw = 'Domain Name: example.com
Registrar: Example Registrar',
                data = {"domainName":"example.com","registrar":"Example Registrar","creationDate":"2020-01-01T00:00:00.000Z"},
        )
        """

    def testClientPendingDomainWhoisData(self):
        """Test ClientPendingDomainWhoisData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
