# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.client_finding_manual_ticket_data import ClientFindingManualTicketData

class TestClientFindingManualTicketData(unittest.TestCase):
    """ClientFindingManualTicketData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientFindingManualTicketData:
        """Test ClientFindingManualTicketData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientFindingManualTicketData`
        """
        model = ClientFindingManualTicketData()
        if include_optional:
            return ClientFindingManualTicketData(
                data = watchtowr_api_sdk.models.client_finding_manual_ticket.ClientFindingManualTicket(
                    id = 1, 
                    user_id = 123, 
                    finding_id = 456, 
                    organisation_id = 789, 
                    board_name = 'Acme Jira Board', 
                    issue_link = 'https://example.atlassian.net/browse/ABC-123', 
                    created_at = '2026-03-09T12:30Z', 
                    updated_at = '2026-03-09T12:30Z', )
            )
        else:
            return ClientFindingManualTicketData(
                data = watchtowr_api_sdk.models.client_finding_manual_ticket.ClientFindingManualTicket(
                    id = 1, 
                    user_id = 123, 
                    finding_id = 456, 
                    organisation_id = 789, 
                    board_name = 'Acme Jira Board', 
                    issue_link = 'https://example.atlassian.net/browse/ABC-123', 
                    created_at = '2026-03-09T12:30Z', 
                    updated_at = '2026-03-09T12:30Z', ),
        )
        """

    def testClientFindingManualTicketData(self):
        """Test ClientFindingManualTicketData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
