# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.invite_client_user_dto import InviteClientUserDto

class TestInviteClientUserDto(unittest.TestCase):
    """InviteClientUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteClientUserDto:
        """Test InviteClientUserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteClientUserDto`
        """
        model = InviteClientUserDto()
        if include_optional:
            return InviteClientUserDto(
                email = 'john.doe@example.com',
                role_type = 'USER',
                business_unit_ids = [1,2]
            )
        else:
            return InviteClientUserDto(
                email = 'john.doe@example.com',
                role_type = 'USER',
        )
        """

    def testInviteClientUserDto(self):
        """Test InviteClientUserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
