# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.ports_api import PortsApi


class TestPortsApi(unittest.TestCase):
    """PortsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortsApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_port_details(self) -> None:
        """Test case for get_asset_port_details

        Get Port
        """
        pass

    def test_get_list_asset_ports(self) -> None:
        """Test case for get_list_asset_ports

        List Ports
        """
        pass


if __name__ == '__main__':
    unittest.main()
