# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.assets_list_response import AssetsListResponse

class TestAssetsListResponse(unittest.TestCase):
    """AssetsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetsListResponse:
        """Test AssetsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetsListResponse`
        """
        model = AssetsListResponse()
        if include_optional:
            return AssetsListResponse(
                data = [{"type":"repository","source":"Initial Data","status":"verified","created_at":"2021-11-22T22:17:12.000Z","id":"1","country":null,"platform":null,"provider":"test provider","url":null,"name":"test name","businessUnits":[],"discovery_reason":"discovery reason test data","owner":"test owner","live":null,"sub_type":null,"super_type":null,"metadata":{}},{"type":"repository","source":"module-github-enumeration-v0.1","status":"verified","created_at":"2021-11-22T22:17:12.000Z","id":"10","country":null,"platform":null,"provider":"github","url":"https://github.com","name":"test-name","businessUnits":[],"discovery_reason":null,"owner":"test-owner","live":null,"sub_type":null,"super_type":null,"metadata":{}},{"type":"subdomain","source":"subdomain.example.com","status":"VerifiedOutOfScope","created_at":"2022-01-20T19:15:56.000Z","id":"4678","country":null,"platform":null,"provider":null,"url":null,"name":"subdomain.example.com","businessUnits":[],"discovery_reason":null,"owner":null,"live":false,"sub_type":null,"super_type":null,"metadata":{}},{"type":"cloudAsset","source":"test-module-controller-1-0","status":"verified","created_at":"2024-06-05T02:31:28.000Z","id":"1","country":null,"platform":null,"provider":null,"url":"123.123.123.123","name":"example-cloudAsset-1","businessUnits":[],"discovery_reason":null,"owner":null,"live":false,"sub_type":"Amazon RDS","super_type":"Databases","metadata":{}}],
                meta = watchtowr_api_sdk.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, )
            )
        else:
            return AssetsListResponse(
                data = [{"type":"repository","source":"Initial Data","status":"verified","created_at":"2021-11-22T22:17:12.000Z","id":"1","country":null,"platform":null,"provider":"test provider","url":null,"name":"test name","businessUnits":[],"discovery_reason":"discovery reason test data","owner":"test owner","live":null,"sub_type":null,"super_type":null,"metadata":{}},{"type":"repository","source":"module-github-enumeration-v0.1","status":"verified","created_at":"2021-11-22T22:17:12.000Z","id":"10","country":null,"platform":null,"provider":"github","url":"https://github.com","name":"test-name","businessUnits":[],"discovery_reason":null,"owner":"test-owner","live":null,"sub_type":null,"super_type":null,"metadata":{}},{"type":"subdomain","source":"subdomain.example.com","status":"VerifiedOutOfScope","created_at":"2022-01-20T19:15:56.000Z","id":"4678","country":null,"platform":null,"provider":null,"url":null,"name":"subdomain.example.com","businessUnits":[],"discovery_reason":null,"owner":null,"live":false,"sub_type":null,"super_type":null,"metadata":{}},{"type":"cloudAsset","source":"test-module-controller-1-0","status":"verified","created_at":"2024-06-05T02:31:28.000Z","id":"1","country":null,"platform":null,"provider":null,"url":"123.123.123.123","name":"example-cloudAsset-1","businessUnits":[],"discovery_reason":null,"owner":null,"live":false,"sub_type":"Amazon RDS","super_type":"Databases","metadata":{}}],
                meta = watchtowr_api_sdk.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, ),
        )
        """

    def testAssetsListResponse(self):
        """Test AssetsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
