# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.subdomains_api import SubdomainsApi


class TestSubdomainsApi(unittest.TestCase):
    """SubdomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubdomainsApi()

    def tearDown(self) -> None:
        pass

    def test_assign_subomain_to_business_units(self) -> None:
        """Test case for assign_subomain_to_business_units

        Assign Subdomain to Business Units
        """
        pass

    def test_create_custom_property_subdomain(self) -> None:
        """Test case for create_custom_property_subdomain

        Create Subdomain Custom Property
        """
        pass

    def test_create_note_subdomain(self) -> None:
        """Test case for create_note_subdomain

        Create Subdomain Note
        """
        pass

    def test_delete_custom_property_subdomain(self) -> None:
        """Test case for delete_custom_property_subdomain

        Delete Subdomain Custom Property
        """
        pass

    def test_delete_note_subdomain(self) -> None:
        """Test case for delete_note_subdomain

        Delete Subdomain Note
        """
        pass

    def test_get_asset_subdomain_details(self) -> None:
        """Test case for get_asset_subdomain_details

        Get Subdomain Details
        """
        pass

    def test_get_asset_subdomain_dns_records(self) -> None:
        """Test case for get_asset_subdomain_dns_records

        List Subdomain DNS Records
        """
        pass

    def test_get_custom_properties_subdomain(self) -> None:
        """Test case for get_custom_properties_subdomain

        List Subdomain Custom Properties
        """
        pass

    def test_get_list_asset_subdomains(self) -> None:
        """Test case for get_list_asset_subdomains

        List Subdomains
        """
        pass

    def test_get_notes_subdomain(self) -> None:
        """Test case for get_notes_subdomain

        List Subdomain Notes
        """
        pass

    def test_unassign_subomain_from_business_units(self) -> None:
        """Test case for unassign_subomain_from_business_units

        Unassign Subdomain from Business Units
        """
        pass

    def test_update_asset_subdomain_status(self) -> None:
        """Test case for update_asset_subdomain_status

        Update Subdomain Status
        """
        pass

    def test_update_custom_property_subdomain(self) -> None:
        """Test case for update_custom_property_subdomain

        Update Subdomain Custom Property
        """
        pass

    def test_update_note_subdomain(self) -> None:
        """Test case for update_note_subdomain

        Update Subdomain Note
        """
        pass


if __name__ == '__main__':
    unittest.main()
