# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.client_active_defense_rule_data import ClientActiveDefenseRuleData

class TestClientActiveDefenseRuleData(unittest.TestCase):
    """ClientActiveDefenseRuleData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientActiveDefenseRuleData:
        """Test ClientActiveDefenseRuleData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientActiveDefenseRuleData`
        """
        model = ClientActiveDefenseRuleData()
        if include_optional:
            return ClientActiveDefenseRuleData(
                data = watchtowr_api_sdk.models.active_defense_rule_details.ActiveDefenseRuleDetails(
                    id = 9001, 
                    name = 'SQL Injection in MOVEit Transfer (CVE-2023-34362)', 
                    description = 'Mitigates exploitation attempts against CVE-2023-34362.', 
                    zero_day = False, 
                    created_at = '2023-12-01T00:00:00.000Z', 
                    updated_at = '2023-12-02T00:00:00.000Z', 
                    rules = [
                        watchtowr_api_sdk.models.active_defense_rule_template.ActiveDefenseRuleTemplate(
                            type = 'cloudflare', 
                            content = { }, )
                        ], 
                    vulnerability = null, 
                    findings_count = 7, 
                    affected_kb_entry_ids = [42,87], )
            )
        else:
            return ClientActiveDefenseRuleData(
                data = watchtowr_api_sdk.models.active_defense_rule_details.ActiveDefenseRuleDetails(
                    id = 9001, 
                    name = 'SQL Injection in MOVEit Transfer (CVE-2023-34362)', 
                    description = 'Mitigates exploitation attempts against CVE-2023-34362.', 
                    zero_day = False, 
                    created_at = '2023-12-01T00:00:00.000Z', 
                    updated_at = '2023-12-02T00:00:00.000Z', 
                    rules = [
                        watchtowr_api_sdk.models.active_defense_rule_template.ActiveDefenseRuleTemplate(
                            type = 'cloudflare', 
                            content = { }, )
                        ], 
                    vulnerability = null, 
                    findings_count = 7, 
                    affected_kb_entry_ids = [42,87], ),
        )
        """

    def testClientActiveDefenseRuleData(self):
        """Test ClientActiveDefenseRuleData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
