# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.api.findings_api import FindingsApi


class TestFindingsApi(unittest.TestCase):
    """FindingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FindingsApi()

    def tearDown(self) -> None:
        pass

    def test_create_custom_property_finding(self) -> None:
        """Test case for create_custom_property_finding

        Create Custom Property
        """
        pass

    def test_create_finding_note(self) -> None:
        """Test case for create_finding_note

        Create Finding Note
        """
        pass

    def test_delete_custom_property_finding(self) -> None:
        """Test case for delete_custom_property_finding

        Delete Custom Property
        """
        pass

    def test_delete_finding_note(self) -> None:
        """Test case for delete_finding_note

        Delete Finding Note
        """
        pass

    def test_export_pdf_for_finding(self) -> None:
        """Test case for export_pdf_for_finding

        Export Finding PDF
        """
        pass

    def test_get_available_finding_statuses(self) -> None:
        """Test case for get_available_finding_statuses

        List Finding Statuses
        """
        pass

    def test_get_custom_properties_finding(self) -> None:
        """Test case for get_custom_properties_finding

        List Custom Properties
        """
        pass

    def test_get_finding_details(self) -> None:
        """Test case for get_finding_details

        Get Finding Details
        """
        pass

    def test_get_finding_notes(self) -> None:
        """Test case for get_finding_notes

        List Finding Notes
        """
        pass

    def test_get_list_findings(self) -> None:
        """Test case for get_list_findings

        List Findings
        """
        pass

    def test_start_specific_finding_retest(self) -> None:
        """Test case for start_specific_finding_retest

        Retest Finding
        """
        pass

    def test_update_custom_property_finding(self) -> None:
        """Test case for update_custom_property_finding

        Update Custom Property
        """
        pass

    def test_update_finding_note(self) -> None:
        """Test case for update_finding_note

        Update Finding Note
        """
        pass

    def test_update_finding_status(self) -> None:
        """Test case for update_finding_status

        Update Finding Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
