# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_client_package_manager import PaginatedClientPackageManager

class TestPaginatedClientPackageManager(unittest.TestCase):
    """PaginatedClientPackageManager unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedClientPackageManager:
        """Test PaginatedClientPackageManager
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedClientPackageManager`
        """
        model = PaginatedClientPackageManager()
        if include_optional:
            return PaginatedClientPackageManager(
                data = [
                    openapi_client.models.client_package_manager.ClientPackageManager(
                        type = 'packageManager', 
                        name = 'example-package', 
                        source = 'module-adversarysight-npmjs-project-discovery', 
                        status = 'verified', 
                        created_at = 2022-02-13T02:10:00.000000Z, 
                        updated_at = 2022-02-13T02:10:00.000000Z, 
                        deleted_at = 2022-02-13T02:10:00.000000Z, 
                        id = 123, 
                        url = 'https://www.npmjs.com/package/example-package', 
                        platform = 'npm', 
                        business_units = [
                            openapi_client.models.client_business_unit.ClientBusinessUnit(
                                id = 1, 
                                name = 'Singapore Business Unit', )
                            ], 
                        custom_properties = [{"id":10,"key":"Severity","value":"normal","isPreset":false,"modelType":"packageManager","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"},{"id":11,"key":"Vulnerability","value":"low risk","isPreset":false,"modelType":"packageManager","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"}], 
                        criticality = 'Medium', )
                    ],
                meta = openapi_client.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, )
            )
        else:
            return PaginatedClientPackageManager(
                data = [
                    openapi_client.models.client_package_manager.ClientPackageManager(
                        type = 'packageManager', 
                        name = 'example-package', 
                        source = 'module-adversarysight-npmjs-project-discovery', 
                        status = 'verified', 
                        created_at = 2022-02-13T02:10:00.000000Z, 
                        updated_at = 2022-02-13T02:10:00.000000Z, 
                        deleted_at = 2022-02-13T02:10:00.000000Z, 
                        id = 123, 
                        url = 'https://www.npmjs.com/package/example-package', 
                        platform = 'npm', 
                        business_units = [
                            openapi_client.models.client_business_unit.ClientBusinessUnit(
                                id = 1, 
                                name = 'Singapore Business Unit', )
                            ], 
                        custom_properties = [{"id":10,"key":"Severity","value":"normal","isPreset":false,"modelType":"packageManager","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"},{"id":11,"key":"Vulnerability","value":"low risk","isPreset":false,"modelType":"packageManager","modelId":209,"createdAt":"2024-09-24T02:37:27.000Z","updatedAt":"2024-09-24T02:38:35.000Z"}], 
                        criticality = 'Medium', )
                    ],
                meta = openapi_client.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, ),
        )
        """

    def testPaginatedClientPackageManager(self):
        """Test PaginatedClientPackageManager"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
