# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.attack_surface_resiliency_dto import AttackSurfaceResiliencyDto

class TestAttackSurfaceResiliencyDto(unittest.TestCase):
    """AttackSurfaceResiliencyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttackSurfaceResiliencyDto:
        """Test AttackSurfaceResiliencyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttackSurfaceResiliencyDto`
        """
        model = AttackSurfaceResiliencyDto()
        if include_optional:
            return AttackSurfaceResiliencyDto(
                concerning_services = 8,
                concerning_points_of_interest = 12,
                valid_credentials = 4,
                open_findings = 45
            )
        else:
            return AttackSurfaceResiliencyDto(
                concerning_services = 8,
                concerning_points_of_interest = 12,
                valid_credentials = 4,
                open_findings = 45,
        )
        """

    def testAttackSurfaceResiliencyDto(self):
        """Test AttackSurfaceResiliencyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
