# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.vuln_detail_kev import VulnDetailKev

class TestVulnDetailKev(unittest.TestCase):
    """VulnDetailKev unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VulnDetailKev:
        """Test VulnDetailKev
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VulnDetailKev`
        """
        model = VulnDetailKev()
        if include_optional:
            return VulnDetailKev(
                cisa_kev_date_added = '2023-06-15T00:00Z',
                vulncheck_kev_date_added = '2023-06-13T00:00Z',
                watchtowr_kev_date_added = '2023-06-12T00:00Z'
            )
        else:
            return VulnDetailKev(
        )
        """

    def testVulnDetailKev(self):
        """Test VulnDetailKev"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
