# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.adversary_intel import AdversaryIntel

class TestAdversaryIntel(unittest.TestCase):
    """AdversaryIntel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdversaryIntel:
        """Test AdversaryIntel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdversaryIntel`
        """
        model = AdversaryIntel()
        if include_optional:
            return AdversaryIntel(
                attacker_id = 1234,
                name = 'Cl0p',
                aliases = ["TA505"],
                type = 'ransomware',
                origin_country_code = 'RU',
                last_reported_date = '2023-12-01T00:00Z',
                victim_countries = watchtowr_api_sdk.models.victim_country_summary.VictimCountrySummary(
                    data = [
                        watchtowr_api_sdk.models.victim_country.VictimCountry(
                            country_code = 'US', 
                            country_name = 'United States', 
                            count = 12, )
                        ], 
                    total_count = 25, ),
                target_industries = watchtowr_api_sdk.models.target_industry_summary.TargetIndustrySummary(
                    data = [
                        watchtowr_api_sdk.models.target_industry.TargetIndustry(
                            name = 'Financial Services', 
                            count = 8, )
                        ], 
                    total_count = 12, ),
                affected_tracked_hunts_count = 3,
                affected_open_findings_count = 7,
                is_affected = True,
                affected_kb_entry_ids = [42,87]
            )
        else:
            return AdversaryIntel(
                attacker_id = 1234,
                name = 'Cl0p',
                type = 'ransomware',
                is_affected = True,
        )
        """

    def testAdversaryIntel(self):
        """Test AdversaryIntel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
