# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hunt_detail_response import HuntDetailResponse

class TestHuntDetailResponse(unittest.TestCase):
    """HuntDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HuntDetailResponse:
        """Test HuntDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HuntDetailResponse`
        """
        model = HuntDetailResponse()
        if include_optional:
            return HuntDetailResponse(
                data = openapi_client.models.hunt_detail.HuntDetail(
                    id = 1, 
                    priority = 'high', 
                    type = 'bespoke', 
                    created_at = '2023-06-28T02:22:36Z', 
                    updated_at = '2023-06-28T02:22:36Z', 
                    total_findings = 1, 
                    total_assets = 10, 
                    hunt_request_type = 'Others', 
                    rapid_exposure_mechanism = 'impactLessPoc', 
                    title = 'Hunt for ITW Exploited Command Injection in Palo Alto Networks GlobalProtect Gateway (CVE-2024-3400)', 
                    description = '"watchTowr performed a PROACTIVE hunt to determine if there are any instances of Palo Alto GlobalProtect Gateway exposed externally.

Successful exploitation of this vulnerability requires several prerequisites, including device telemetry being enabled on the affected instance. 

As details of the vulnerability have been discovered, analysed and reproduced by watchTowr, impact-less proof-of-concept payload(s) will be used to determine if it is possible to abuse the vulnerabilities.

Additionally, it is recommended that any affected instances are reviewed for anomalous activity and behaviour that could indicate the prior exploitation of this vulnerability.

Should any instances of Palo Alto GlobalProtect Gateway be identified, they will be attached to this hunt."
', 
                    hypothesis = '"A security advisory has been published by Palo Alto regarding a critical security vulnerability affecting Palo Alto Networks GlobalProtect Gateway. This vulnerability is tracked as CVE-2024-3400.

This vulnerability could allow an unauthenticated attacker to execute arbitrary code with root privileges on the firewall. Palo Alto have stated exploitation of this vulnerability has been observed in the wild.

The following versions of PAN-OS are affected by the vulnerability:

* PAN-OS version 11.1 - versions lower than 11.1.2-h3
* PAN-OS version 11.0 - versions lower than 11.0.4-h1
* PAN-OS version 10.2 - versions lower than 10.2.9-h1

Palo Alto state that the GlobalProtect gateway and device telemetry must be enabled for an appliance to be vulnerable."
', 
                    references = ["https://security.paloaltonetworks.com/CVE-2024-3400"], 
                    completed_at = '2023-06-28T02:22:36Z', 
                    completed_by = 'Steve', 
                    requested_by = 'John Smith', 
                    status = 'completed', )
            )
        else:
            return HuntDetailResponse(
                data = openapi_client.models.hunt_detail.HuntDetail(
                    id = 1, 
                    priority = 'high', 
                    type = 'bespoke', 
                    created_at = '2023-06-28T02:22:36Z', 
                    updated_at = '2023-06-28T02:22:36Z', 
                    total_findings = 1, 
                    total_assets = 10, 
                    hunt_request_type = 'Others', 
                    rapid_exposure_mechanism = 'impactLessPoc', 
                    title = 'Hunt for ITW Exploited Command Injection in Palo Alto Networks GlobalProtect Gateway (CVE-2024-3400)', 
                    description = '"watchTowr performed a PROACTIVE hunt to determine if there are any instances of Palo Alto GlobalProtect Gateway exposed externally.

Successful exploitation of this vulnerability requires several prerequisites, including device telemetry being enabled on the affected instance. 

As details of the vulnerability have been discovered, analysed and reproduced by watchTowr, impact-less proof-of-concept payload(s) will be used to determine if it is possible to abuse the vulnerabilities.

Additionally, it is recommended that any affected instances are reviewed for anomalous activity and behaviour that could indicate the prior exploitation of this vulnerability.

Should any instances of Palo Alto GlobalProtect Gateway be identified, they will be attached to this hunt."
', 
                    hypothesis = '"A security advisory has been published by Palo Alto regarding a critical security vulnerability affecting Palo Alto Networks GlobalProtect Gateway. This vulnerability is tracked as CVE-2024-3400.

This vulnerability could allow an unauthenticated attacker to execute arbitrary code with root privileges on the firewall. Palo Alto have stated exploitation of this vulnerability has been observed in the wild.

The following versions of PAN-OS are affected by the vulnerability:

* PAN-OS version 11.1 - versions lower than 11.1.2-h3
* PAN-OS version 11.0 - versions lower than 11.0.4-h1
* PAN-OS version 10.2 - versions lower than 10.2.9-h1

Palo Alto state that the GlobalProtect gateway and device telemetry must be enabled for an appliance to be vulnerable."
', 
                    references = ["https://security.paloaltonetworks.com/CVE-2024-3400"], 
                    completed_at = '2023-06-28T02:22:36Z', 
                    completed_by = 'Steve', 
                    requested_by = 'John Smith', 
                    status = 'completed', ),
        )
        """

    def testHuntDetailResponse(self):
        """Test HuntDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
