# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.target_industry_summary import TargetIndustrySummary

class TestTargetIndustrySummary(unittest.TestCase):
    """TargetIndustrySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TargetIndustrySummary:
        """Test TargetIndustrySummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TargetIndustrySummary`
        """
        model = TargetIndustrySummary()
        if include_optional:
            return TargetIndustrySummary(
                data = [
                    watchtowr_api_sdk.models.target_industry.TargetIndustry(
                        name = 'Financial Services', 
                        count = 8, )
                    ],
                total_count = 12
            )
        else:
            return TargetIndustrySummary(
        )
        """

    def testTargetIndustrySummary(self):
        """Test TargetIndustrySummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
