# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ip_addresses_api import IPAddressesApi


class TestIPAddressesApi(unittest.TestCase):
    """IPAddressesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IPAddressesApi()

    def tearDown(self) -> None:
        pass

    def test_assign_ip_to_business_units(self) -> None:
        """Test case for assign_ip_to_business_units

        Assign IP to Business Units
        """
        pass

    def test_create_asset_ip_note(self) -> None:
        """Test case for create_asset_ip_note

        Create Note
        """
        pass

    def test_create_custom_property_ip(self) -> None:
        """Test case for create_custom_property_ip

        Create Custom Property
        """
        pass

    def test_delete_asset_ip_note(self) -> None:
        """Test case for delete_asset_ip_note

        Delete Note
        """
        pass

    def test_delete_custom_property_ip(self) -> None:
        """Test case for delete_custom_property_ip

        Delete Custom Property
        """
        pass

    def test_get_asset_ip_details(self) -> None:
        """Test case for get_asset_ip_details

        Get IP Address Details
        """
        pass

    def test_get_asset_ip_dns_records(self) -> None:
        """Test case for get_asset_ip_dns_records

        List DNS Records
        """
        pass

    def test_get_asset_ip_notes(self) -> None:
        """Test case for get_asset_ip_notes

        List Notes
        """
        pass

    def test_get_asset_ip_port_details(self) -> None:
        """Test case for get_asset_ip_port_details

        Get Port
        """
        pass

    def test_get_asset_ip_ports(self) -> None:
        """Test case for get_asset_ip_ports

        List Ports
        """
        pass

    def test_get_custom_properties_ip(self) -> None:
        """Test case for get_custom_properties_ip

        List Custom Properties
        """
        pass

    def test_get_list_asset_ips(self) -> None:
        """Test case for get_list_asset_ips

        List IP Addresses
        """
        pass

    def test_unassign_ip_from_business_units(self) -> None:
        """Test case for unassign_ip_from_business_units

        Unassign IP from Business Units
        """
        pass

    def test_update_asset_ip_note(self) -> None:
        """Test case for update_asset_ip_note

        Update Note
        """
        pass

    def test_update_asset_ip_status(self) -> None:
        """Test case for update_asset_ip_status

        Update Status
        """
        pass

    def test_update_custom_property_ip(self) -> None:
        """Test case for update_custom_property_ip

        Update Custom Property
        """
        pass


if __name__ == '__main__':
    unittest.main()
