# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.adversary_intel_details import AdversaryIntelDetails

class TestAdversaryIntelDetails(unittest.TestCase):
    """AdversaryIntelDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdversaryIntelDetails:
        """Test AdversaryIntelDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdversaryIntelDetails`
        """
        model = AdversaryIntelDetails()
        if include_optional:
            return AdversaryIntelDetails(
                attacker_id = 1234,
                name = 'Cl0p',
                type = 'ransomware',
                description = 'A financially motivated ransomware group.',
                aliases = ["TA505"],
                country_code = 'RU',
                first_reported_date = '2019-02-01T00:00Z',
                vulnerability_last_updated = '2023-12-01T00:00Z',
                mitre_last_updated = '2023-12-01T00:00Z',
                victim_countries = watchtowr_api_sdk.models.victim_country_summary.VictimCountrySummary(
                    data = [
                        watchtowr_api_sdk.models.victim_country.VictimCountry(
                            country_code = 'US', 
                            country_name = 'United States', 
                            count = 12, )
                        ], 
                    total_count = 25, ),
                target_industries = watchtowr_api_sdk.models.target_industry_summary.TargetIndustrySummary(
                    data = [
                        watchtowr_api_sdk.models.target_industry.TargetIndustry(
                            name = 'Financial Services', 
                            count = 8, )
                        ], 
                    total_count = 12, ),
                latest_media = [
                    watchtowr_api_sdk.models.media.Media(
                        url = 'https://example.com/article', 
                        title = 'Example article title', 
                        published_at = '2023-12-01T00:00Z', )
                    ],
                is_affected = True,
                affected_kb_entry_ids = [42,87]
            )
        else:
            return AdversaryIntelDetails(
                attacker_id = 1234,
                name = 'Cl0p',
                is_affected = True,
                affected_kb_entry_ids = [42,87],
        )
        """

    def testAdversaryIntelDetails(self):
        """Test AdversaryIntelDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
