# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.required_actions_dto import RequiredActionsDto

class TestRequiredActionsDto(unittest.TestCase):
    """RequiredActionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequiredActionsDto:
        """Test RequiredActionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequiredActionsDto`
        """
        model = RequiredActionsDto()
        if include_optional:
            return RequiredActionsDto(
                actively_exploited_findings = 5,
                unresolved_rapid_reaction_hunts = 3
            )
        else:
            return RequiredActionsDto(
                actively_exploited_findings = 5,
                unresolved_rapid_reaction_hunts = 3,
        )
        """

    def testRequiredActionsDto(self):
        """Test RequiredActionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
