# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.kb_entry_cwe import KbEntryCwe

class TestKbEntryCwe(unittest.TestCase):
    """KbEntryCwe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KbEntryCwe:
        """Test KbEntryCwe
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KbEntryCwe`
        """
        model = KbEntryCwe()
        if include_optional:
            return KbEntryCwe(
                cwe_id = 'CWE-89',
                name = 'Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')'
            )
        else:
            return KbEntryCwe(
        )
        """

    def testKbEntryCwe(self):
        """Test KbEntryCwe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
