# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.client_business_unit_detail_with_rules_data import ClientBusinessUnitDetailWithRulesData

class TestClientBusinessUnitDetailWithRulesData(unittest.TestCase):
    """ClientBusinessUnitDetailWithRulesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientBusinessUnitDetailWithRulesData:
        """Test ClientBusinessUnitDetailWithRulesData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientBusinessUnitDetailWithRulesData`
        """
        model = ClientBusinessUnitDetailWithRulesData()
        if include_optional:
            return ClientBusinessUnitDetailWithRulesData(
                data = watchtowr_api_sdk.models.client_business_unit_detail_with_rules.ClientBusinessUnitDetailWithRules(
                    id = 1, 
                    name = 'Singapore Business Unit', 
                    description = 'Singapore based assets', 
                    type = 'DEPARTMENT', 
                    parent_id = 1, 
                    created_at = 2022-02-13T02:10:00.000000Z, 
                    updated_at = 2022-02-13T02:10:00.000000Z, 
                    rules = watchtowr_api_sdk.models.rules.rules(), )
            )
        else:
            return ClientBusinessUnitDetailWithRulesData(
                data = watchtowr_api_sdk.models.client_business_unit_detail_with_rules.ClientBusinessUnitDetailWithRules(
                    id = 1, 
                    name = 'Singapore Business Unit', 
                    description = 'Singapore based assets', 
                    type = 'DEPARTMENT', 
                    parent_id = 1, 
                    created_at = 2022-02-13T02:10:00.000000Z, 
                    updated_at = 2022-02-13T02:10:00.000000Z, 
                    rules = watchtowr_api_sdk.models.rules.rules(), ),
        )
        """

    def testClientBusinessUnitDetailWithRulesData(self):
        """Test ClientBusinessUnitDetailWithRulesData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
