# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.create_organisation_whitelist_ip_dto import CreateOrganisationWhitelistIpDto

class TestCreateOrganisationWhitelistIpDto(unittest.TestCase):
    """CreateOrganisationWhitelistIpDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrganisationWhitelistIpDto:
        """Test CreateOrganisationWhitelistIpDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrganisationWhitelistIpDto`
        """
        model = CreateOrganisationWhitelistIpDto()
        if include_optional:
            return CreateOrganisationWhitelistIpDto(
                ip = '192.168.1.1',
                description = 'Office network'
            )
        else:
            return CreateOrganisationWhitelistIpDto(
                ip = '192.168.1.1',
        )
        """

    def testCreateOrganisationWhitelistIpDto(self):
        """Test CreateOrganisationWhitelistIpDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
