# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.whitelist_ip_data import WhitelistIpData

class TestWhitelistIpData(unittest.TestCase):
    """WhitelistIpData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhitelistIpData:
        """Test WhitelistIpData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhitelistIpData`
        """
        model = WhitelistIpData()
        if include_optional:
            return WhitelistIpData(
                id = 1,
                ip = '192.168.1.1',
                description = 'Office network',
                created_at = '2024-01-01T00:00Z',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return WhitelistIpData(
                id = 1,
                ip = '192.168.1.1',
                description = 'Office network',
                created_at = '2024-01-01T00:00Z',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testWhitelistIpData(self):
        """Test WhitelistIpData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
