# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cloud_integration_assets_api import CloudIntegrationAssetsApi


class TestCloudIntegrationAssetsApi(unittest.TestCase):
    """CloudIntegrationAssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CloudIntegrationAssetsApi()

    def tearDown(self) -> None:
        pass

    def test_add_asset_cloud_asset_note(self) -> None:
        """Test case for add_asset_cloud_asset_note

        Create Note
        """
        pass

    def test_assign_cloud_asset_to_business_units(self) -> None:
        """Test case for assign_cloud_asset_to_business_units

        Assign Cloud Integration Asset to Business Units
        """
        pass

    def test_create_custom_property_cloud_asset(self) -> None:
        """Test case for create_custom_property_cloud_asset

        Create Custom Property
        """
        pass

    def test_delete_asset_cloud_asset_note(self) -> None:
        """Test case for delete_asset_cloud_asset_note

        Delete Note
        """
        pass

    def test_delete_custom_property_cloud_asset(self) -> None:
        """Test case for delete_custom_property_cloud_asset

        Delete Custom Property
        """
        pass

    def test_get_asset_cloud_asset_details(self) -> None:
        """Test case for get_asset_cloud_asset_details

        Get Cloud Asset Details
        """
        pass

    def test_get_asset_cloud_asset_notes(self) -> None:
        """Test case for get_asset_cloud_asset_notes

        List Notes
        """
        pass

    def test_get_custom_properties_cloud_asset(self) -> None:
        """Test case for get_custom_properties_cloud_asset

        List Custom Properties
        """
        pass

    def test_get_list_asset_cloud_asset(self) -> None:
        """Test case for get_list_asset_cloud_asset

        List Cloud Assets
        """
        pass

    def test_unassign_cloud_asset_from_business_units(self) -> None:
        """Test case for unassign_cloud_asset_from_business_units

        Unassign Cloud Integration Asset from Business Units
        """
        pass

    def test_update_asset_cloud_asset_note(self) -> None:
        """Test case for update_asset_cloud_asset_note

        Update Note
        """
        pass

    def test_update_asset_cloud_asset_status(self) -> None:
        """Test case for update_asset_cloud_asset_status

        Update Cloud Asset Status
        """
        pass

    def test_update_custom_property_cloud_asset(self) -> None:
        """Test case for update_custom_property_cloud_asset

        Update Custom Property
        """
        pass


if __name__ == '__main__':
    unittest.main()
