# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.client_activity_log import ClientActivityLog

class TestClientActivityLog(unittest.TestCase):
    """ClientActivityLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientActivityLog:
        """Test ClientActivityLog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientActivityLog`
        """
        model = ClientActivityLog()
        if include_optional:
            return ClientActivityLog(
                id = 1,
                description = Successful login from 123.123.123.123,
                type = Successful Login,
                properties = {"attributes": {"ip": "123.123.123.123"}},
                created_at = 2022-02-22 22:00:00,
                caused_by = watchtowr_api_sdk.models.causer.Causer(
                    id = 1, 
                    name = Example, )
            )
        else:
            return ClientActivityLog(
                id = 1,
                description = Successful login from 123.123.123.123,
                type = Successful Login,
                caused_by = watchtowr_api_sdk.models.causer.Causer(
                    id = 1, 
                    name = Example, ),
        )
        """

    def testClientActivityLog(self):
        """Test ClientActivityLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
