# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api_sdk.models.ttp_library_item import TtpLibraryItem

class TestTtpLibraryItem(unittest.TestCase):
    """TtpLibraryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TtpLibraryItem:
        """Test TtpLibraryItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TtpLibraryItem`
        """
        model = TtpLibraryItem()
        if include_optional:
            return TtpLibraryItem(
                id = 789,
                name = 'CVE-2024-3400 - PAN-OS GlobalProtect Gateway Command Injection',
                identifier = 'CVE-2024-3400',
                type = 'AdversarySight',
                category = watchtowr_api_sdk.models.ttp_library_category_item.TtpLibraryCategoryItem(
                    id = 42, 
                    name = 'Network Infrastructure', ),
                module = 'module-panos-cve-2024-3400-v1.0',
                enabled_on = '2024-04-16T00:00Z'
            )
        else:
            return TtpLibraryItem(
                id = 789,
                name = 'CVE-2024-3400 - PAN-OS GlobalProtect Gateway Command Injection',
                identifier = 'CVE-2024-3400',
                type = 'AdversarySight',
                category = watchtowr_api_sdk.models.ttp_library_category_item.TtpLibraryCategoryItem(
                    id = 42, 
                    name = 'Network Infrastructure', ),
        )
        """

    def testTtpLibraryItem(self):
        """Test TtpLibraryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
