# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hunts_api import HuntsApi


class TestHuntsApi(unittest.TestCase):
    """HuntsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HuntsApi()

    def tearDown(self) -> None:
        pass

    def test_get_client_hunts(self) -> None:
        """Test case for get_client_hunts

        List Hunts
        """
        pass

    def test_get_list_asset_by_hunt(self) -> None:
        """Test case for get_list_asset_by_hunt

        List Assets
        """
        pass

    def test_get_list_finding_by_hunt(self) -> None:
        """Test case for get_list_finding_by_hunt

        List Hunt Findings
        """
        pass

    def test_show_the_detail_hunt(self) -> None:
        """Test case for show_the_detail_hunt

        Get Hunt Details
        """
        pass


if __name__ == '__main__':
    unittest.main()
