"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated
from watchtowr_complete_watchtowr_platform_api_documentation_python import utils
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class AssetAndBusinessUnitAlreadyAssociatedConflictErrorResponseData(BaseModel):
    message: str

    status_code: Annotated[float, pydantic.Field(alias="statusCode")]

    error: str


class AssetAndBusinessUnitAlreadyAssociatedConflictErrorResponse(Exception):
    data: AssetAndBusinessUnitAlreadyAssociatedConflictErrorResponseData

    def __init__(
        self, data: AssetAndBusinessUnitAlreadyAssociatedConflictErrorResponseData
    ):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, AssetAndBusinessUnitAlreadyAssociatedConflictErrorResponseData
        )
