"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asset import Asset, AssetTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class AssetsListResponseTypedDict(TypedDict):
    data: List[AssetTypedDict]
    meta: MetaTypedDict


class AssetsListResponse(BaseModel):
    data: List[Asset]

    meta: Meta
