"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class AttackSurfaceDtoTypedDict(TypedDict):
    total_verified_assets: float
    r"""Total count of verified assets"""
    total_points_of_interest: float
    r"""Total count of points of interest"""
    total_network_services: float
    r"""Total count of network services"""
    total_certificates: float
    r"""Total count of TLS/SSL certificates"""


class AttackSurfaceDto(BaseModel):
    total_verified_assets: Annotated[float, pydantic.Field(alias="totalVerifiedAssets")]
    r"""Total count of verified assets"""

    total_points_of_interest: Annotated[
        float, pydantic.Field(alias="totalPointsOfInterest")
    ]
    r"""Total count of points of interest"""

    total_network_services: Annotated[
        float, pydantic.Field(alias="totalNetworkServices")
    ]
    r"""Total count of network services"""

    total_certificates: Annotated[float, pydantic.Field(alias="totalCertificates")]
    r"""Total count of TLS/SSL certificates"""
