"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class NameTypedDict(TypedDict):
    r"""User name"""


class Name(BaseModel):
    r"""User name"""


class CauserTypedDict(TypedDict):
    id: float
    r"""ID"""
    name: NameTypedDict
    r"""User name"""


class Causer(BaseModel):
    id: float
    r"""ID"""

    name: Name
    r"""User name"""
