"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientrepository import ClientRepository, ClientRepositoryTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientRepositoryDataTypedDict(TypedDict):
    data: ClientRepositoryTypedDict


class ClientRepositoryData(BaseModel):
    data: ClientRepository
