"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientEngineSettingsDetailsTypedDict(TypedDict):
    adversary_sight_enabled: bool
    r"""Indicates whether the Adversary Sight engine coverage is enabled for the asset."""
    automated_red_teaming_enabled: bool
    r"""Indicates whether the Automated Red Teaming engine coverage is enabled for the asset."""
    credential_stuffing_enabled: bool
    r"""Indicates whether the Credential Stuffing engine coverage is enabled for the asset."""
    dns_bruteforcing_enabled: bool
    r"""Indicates whether the DNS Bruteforcing engine coverage is enabled for the asset."""
    rapid_reaction_enabled: bool
    r"""Indicates whether the Rapid Reaction engine coverage is enabled for the asset"""
    intrusive_http_checks_enabled: bool
    r"""Indicates whether the Intrusive HTTP Check engine coverage is enabled for the asset."""
    id: float
    r"""The asset ID"""
    type: str
    r"""The asset type"""


class ClientEngineSettingsDetails(BaseModel):
    adversary_sight_enabled: Annotated[
        bool, pydantic.Field(alias="adversarySightEnabled")
    ]
    r"""Indicates whether the Adversary Sight engine coverage is enabled for the asset."""

    automated_red_teaming_enabled: Annotated[
        bool, pydantic.Field(alias="automatedRedTeamingEnabled")
    ]
    r"""Indicates whether the Automated Red Teaming engine coverage is enabled for the asset."""

    credential_stuffing_enabled: Annotated[
        bool, pydantic.Field(alias="credentialStuffingEnabled")
    ]
    r"""Indicates whether the Credential Stuffing engine coverage is enabled for the asset."""

    dns_bruteforcing_enabled: Annotated[
        bool, pydantic.Field(alias="dnsBruteforcingEnabled")
    ]
    r"""Indicates whether the DNS Bruteforcing engine coverage is enabled for the asset."""

    rapid_reaction_enabled: Annotated[
        bool, pydantic.Field(alias="rapidReactionEnabled")
    ]
    r"""Indicates whether the Rapid Reaction engine coverage is enabled for the asset"""

    intrusive_http_checks_enabled: Annotated[
        bool, pydantic.Field(alias="intrusiveHttpChecksEnabled")
    ]
    r"""Indicates whether the Intrusive HTTP Check engine coverage is enabled for the asset."""

    id: float
    r"""The asset ID"""

    type: str
    r"""The asset type"""
