"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientBusinessUnitDetailWithRulesCreatedAtTypedDict(TypedDict):
    r"""Created At"""


class ClientBusinessUnitDetailWithRulesCreatedAt(BaseModel):
    r"""Created At"""


class ClientBusinessUnitDetailWithRulesUpdatedAtTypedDict(TypedDict):
    r"""Updated At"""


class ClientBusinessUnitDetailWithRulesUpdatedAt(BaseModel):
    r"""Updated At"""


class RulesTypedDict(TypedDict):
    r"""Paginated rules for this business unit"""


class Rules(BaseModel):
    r"""Paginated rules for this business unit"""


class ClientBusinessUnitDetailWithRulesTypedDict(TypedDict):
    id: float
    r"""ID"""
    name: str
    r"""Name"""
    description: str
    r"""Description"""
    type: str
    r"""Business unit type"""
    created_at: ClientBusinessUnitDetailWithRulesCreatedAtTypedDict
    r"""Created At"""
    updated_at: ClientBusinessUnitDetailWithRulesUpdatedAtTypedDict
    r"""Updated At"""
    rules: RulesTypedDict
    r"""Paginated rules for this business unit"""
    parent_id: NotRequired[float]
    r"""Parent business unit ID"""
    user_ids: NotRequired[List[float]]
    r"""Array of user IDs assigned to this business unit"""


class ClientBusinessUnitDetailWithRules(BaseModel):
    id: float
    r"""ID"""

    name: str
    r"""Name"""

    description: str
    r"""Description"""

    type: str
    r"""Business unit type"""

    created_at: ClientBusinessUnitDetailWithRulesCreatedAt
    r"""Created At"""

    updated_at: ClientBusinessUnitDetailWithRulesUpdatedAt
    r"""Updated At"""

    rules: Rules
    r"""Paginated rules for this business unit"""

    parent_id: Optional[float] = None
    r"""Parent business unit ID"""

    user_ids: Optional[List[float]] = None
    r"""Array of user IDs assigned to this business unit"""
