"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientiprelateddnsrecord import (
    ClientIPRelatedDNSRecord,
    ClientIPRelatedDNSRecordTypedDict,
)
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientIPDNSRecordPointingAtDataTypedDict(TypedDict):
    data: List[ClientIPRelatedDNSRecordTypedDict]
    meta: MetaTypedDict


class ClientIPDNSRecordPointingAtData(BaseModel):
    data: List[ClientIPRelatedDNSRecord]

    meta: Meta
