"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientIPDetailDNSRecordsTypedDict(TypedDict):
    dns_records_owned: List[str]
    dns_records_pointing_at: List[str]


class ClientIPDetailDNSRecords(BaseModel):
    dns_records_owned: List[str]

    dns_records_pointing_at: List[str]
