"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientSeedDataBusinessUnitTypedDict(TypedDict):
    id: float
    r"""Business Unit ID"""
    name: str
    r"""Business Unit name"""
    type: str
    r"""Business Unit type"""
    created_at: datetime
    r"""Creation date"""
    updated_at: datetime
    r"""Last update date"""
    description: NotRequired[str]
    r"""Business Unit description"""


class ClientSeedDataBusinessUnit(BaseModel):
    id: float
    r"""Business Unit ID"""

    name: str
    r"""Business Unit name"""

    type: str
    r"""Business Unit type"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Creation date"""

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]
    r"""Last update date"""

    description: Optional[str] = None
    r"""Business Unit description"""
