"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
    Nullable,
    UNSET_SENTINEL,
)


class ClientDNSRecordAssetTypedDict(TypedDict):
    r"""Asset information"""

    id: float
    r"""Asset ID"""
    name: str
    r"""Asset name"""
    type: str
    r"""Asset type"""


class ClientDNSRecordAsset(BaseModel):
    r"""Asset information"""

    id: float
    r"""Asset ID"""

    name: str
    r"""Asset name"""

    type: str
    r"""Asset type"""


class ClientDNSRecordTypedDict(TypedDict):
    id: float
    r"""DNS Record ID"""
    asset: Nullable[ClientDNSRecordAssetTypedDict]
    r"""Asset information"""
    record_name: str
    r"""Identifies the resource this record resolves to."""
    type: str
    r"""The DNS record type defines the purpose or function of the record, such as domain name resolution, email routing, and more."""
    ttl: float
    r"""Time to live (TTL) controls how long each record is cached by resolvers."""
    value: str
    r"""The value of a DNS record, depending on the record type. For example, the IP address of the origin server that hosts the web content served by an A or AAAA record."""
    created_at: datetime
    r"""Creation date"""


class ClientDNSRecord(BaseModel):
    id: float
    r"""DNS Record ID"""

    asset: Nullable[ClientDNSRecordAsset]
    r"""Asset information"""

    record_name: Annotated[str, pydantic.Field(alias="recordName")]
    r"""Identifies the resource this record resolves to."""

    type: str
    r"""The DNS record type defines the purpose or function of the record, such as domain name resolution, email routing, and more."""

    ttl: float
    r"""Time to live (TTL) controls how long each record is cached by resolvers."""

    value: str
    r"""The value of a DNS record, depending on the record type. For example, the IP address of the origin server that hosts the web content served by an A or AAAA record."""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    r"""Creation date"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["asset"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
