"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientiprange import ClientIPRange, ClientIPRangeTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientIPRangeDataTypedDict(TypedDict):
    data: ClientIPRangeTypedDict


class ClientIPRangeData(BaseModel):
    data: ClientIPRange
