"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientcloudasset import ClientCloudAsset, ClientCloudAssetTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientCloudAssetDataTypedDict(TypedDict):
    data: ClientCloudAssetTypedDict


class ClientCloudAssetData(BaseModel):
    data: ClientCloudAsset
