"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class RoleTypedDict(TypedDict):
    r"""User role information"""


class Role(BaseModel):
    r"""User role information"""


class BusinessUnitsTypedDict(TypedDict):
    id: NotRequired[float]
    name: NotRequired[str]


class BusinessUnits(BaseModel):
    id: Optional[float] = None

    name: Optional[str] = None


class ClientUserDetailTypedDict(TypedDict):
    id: float
    r"""User ID"""
    name: str
    r"""User name"""
    email: str
    r"""User email"""
    title: str
    r"""User title"""
    mobile_phone_number: str
    r"""Mobile phone number (masked)"""
    office_phone_number: str
    r"""Office phone number (masked)"""
    created_at: datetime
    r"""Created at timestamp"""
    locked: bool
    r"""Whether user is locked"""
    role: RoleTypedDict
    r"""User role information"""
    business_units: List[BusinessUnitsTypedDict]
    r"""User business unit assignments"""


class ClientUserDetail(BaseModel):
    id: float
    r"""User ID"""

    name: str
    r"""User name"""

    email: str
    r"""User email"""

    title: str
    r"""User title"""

    mobile_phone_number: str
    r"""Mobile phone number (masked)"""

    office_phone_number: str
    r"""Office phone number (masked)"""

    created_at: datetime
    r"""Created at timestamp"""

    locked: bool
    r"""Whether user is locked"""

    role: Role
    r"""User role information"""

    business_units: Annotated[
        List[BusinessUnits], pydantic.Field(alias="businessUnits")
    ]
    r"""User business unit assignments"""
