"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientcustomproperty import ClientCustomProperty, ClientCustomPropertyTypedDict
from datetime import datetime
from enum import Enum
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ClientAPIDocumentationAssetStatus(str, Enum):
    VERIFIED = "verified"
    UNREGISTERED = "Unregistered"
    INCORRECT_IDENTIFICATION = "Incorrect Identification"
    PENDING = "pending"
    VERIFIED_OUT_OF_SCOPE = "VerifiedOutOfScope"
    VERIFIED_REDUCED_ATTACK = "VerifiedReducedAttack"
    TRACKED = "Tracked"


class ClientAPIDocumentationAssetTypedDict(TypedDict):
    id: float
    type: str
    name: str
    source: str
    platform: str
    status: ClientAPIDocumentationAssetStatus
    created_at: datetime
    url: str
    custom_properties: List[ClientCustomPropertyTypedDict]
    criticality: str


class ClientAPIDocumentationAsset(BaseModel):
    id: float

    type: str

    name: str

    source: str

    platform: str

    status: ClientAPIDocumentationAssetStatus

    created_at: datetime

    url: str

    custom_properties: Annotated[
        List[ClientCustomProperty], pydantic.Field(alias="customProperties")
    ]

    criticality: str
