"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createclientcustompropertydto import (
    CreateClientCustomPropertyDto,
    CreateClientCustomPropertyDtoTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class CreateCustomPropertyAPIDocumentationRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of the API Documentation asset to create a new custom property for."""
    create_client_custom_property_dto: CreateClientCustomPropertyDtoTypedDict


class CreateCustomPropertyAPIDocumentationRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of the API Documentation asset to create a new custom property for."""

    create_client_custom_property_dto: Annotated[
        CreateClientCustomPropertyDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
