"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class CreateClientNoteDtoTypedDict(TypedDict):
    note: str
    r"""Content of the note."""
    title: NotRequired[str]
    r"""Title of the note."""


class CreateClientNoteDto(BaseModel):
    note: str
    r"""Content of the note."""

    title: Optional[str] = None
    r"""Title of the note."""
