"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
)


class DeleteFindingNoteRequestTypedDict(TypedDict):
    id: float
    r"""The ID of the finding that contains the note."""
    note_id: float
    r"""The ID of the note to delete."""


class DeleteFindingNoteRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the finding that contains the note."""

    note_id: Annotated[
        float,
        pydantic.Field(alias="noteId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the note to delete."""
