"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from watchtowr_complete_watchtowr_platform_api_documentation_python import utils
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ForbiddenResponseData(BaseModel):
    message: str
    r"""Error message"""


class ForbiddenResponse(Exception):
    data: ForbiddenResponseData

    def __init__(self, data: ForbiddenResponseData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ForbiddenResponseData)
