"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
)


class GetAssetCloudAssetDetailsRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of the Cloud Integration Asset to retrieve."""


class GetAssetCloudAssetDetailsRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of the Cloud Integration Asset to retrieve."""
