"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    QueryParamMetadata,
)


class QueryParamSortBy(str, Enum):
    r"""Sort by field"""

    UPDATED_AT = "updated_at"
    CREATED_AT = "created_at"


class SortOrder(str, Enum):
    r"""Sort order"""

    ASC = "ASC"
    DESC = "DESC"


class GetListFindingRetestHistoryRequestTypedDict(TypedDict):
    page: NotRequired[float]
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""
    page_size: NotRequired[float]
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30."""
    business_unit_ids: NotRequired[str]
    r"""Filter assets by a list of comma separated business unit IDs that the asset is related to."""
    sort_by: NotRequired[QueryParamSortBy]
    r"""Sort by field"""
    sort_order: NotRequired[SortOrder]
    r"""Sort order"""


class GetListFindingRetestHistoryRequest(BaseModel):
    page: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""

    page_size: Annotated[
        Optional[float],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30."""

    business_unit_ids: Annotated[
        Optional[str],
        pydantic.Field(alias="businessUnitIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter assets by a list of comma separated business unit IDs that the asset is related to."""

    sort_by: Annotated[
        Optional[QueryParamSortBy],
        pydantic.Field(alias="sortBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = QueryParamSortBy.CREATED_AT
    r"""Sort by field"""

    sort_order: Annotated[
        Optional[SortOrder],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = SortOrder.DESC
    r"""Sort order"""
