"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    QueryParamMetadata,
)


class GetListAssetPortsRequestTypedDict(TypedDict):
    page: NotRequired[float]
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""
    page_size: NotRequired[float]
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 100."""
    include_closed_port: NotRequired[bool]
    r"""Include listings with closed ports."""
    include_no_service: NotRequired[bool]
    r"""Include listings without a service"""
    created_from: NotRequired[datetime]
    r"""Filter ports created after a given date and time."""
    created_to: NotRequired[datetime]
    r"""Filter ports created before a given date and time."""
    asset_name: NotRequired[str]
    r"""Search ports by port number."""
    business_unit_ids: NotRequired[str]
    r"""Filter assets by a list of comma separated business unit IDs that the asset is related to."""
    custom_property_key: NotRequired[str]
    r"""Filter assets by custom property key."""
    custom_property_value: NotRequired[str]
    r"""Filter assets by custom property value. Must be used together with customPropertyKey."""


class GetListAssetPortsRequest(BaseModel):
    page: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""

    page_size: Annotated[
        Optional[float],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 100."""

    include_closed_port: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeClosedPort"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Include listings with closed ports."""

    include_no_service: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeNoService"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Include listings without a service"""

    created_from: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter ports created after a given date and time."""

    created_to: Annotated[
        Optional[datetime],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter ports created before a given date and time."""

    asset_name: Annotated[
        Optional[str],
        pydantic.Field(alias="assetName"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Search ports by port number."""

    business_unit_ids: Annotated[
        Optional[str],
        pydantic.Field(alias="businessUnitIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter assets by a list of comma separated business unit IDs that the asset is related to."""

    custom_property_key: Annotated[
        Optional[str],
        pydantic.Field(alias="customPropertyKey"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter assets by custom property key."""

    custom_property_value: Annotated[
        Optional[str],
        pydantic.Field(alias="customPropertyValue"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter assets by custom property value. Must be used together with customPropertyKey."""
