"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class HostnameBusinessUnitIDsDTOTypedDict(TypedDict):
    business_unit_ids: List[str]
    r"""List of business unit IDs to assign the asset to."""
    cascade_subdomain: bool
    r"""Cascade business units to domain's subdomains"""
    cascade_ip: bool
    r"""Cascade business units to domain's ipaddresses"""


class HostnameBusinessUnitIDsDTO(BaseModel):
    business_unit_ids: Annotated[List[str], pydantic.Field(alias="businessUnitIds")]
    r"""List of business unit IDs to assign the asset to."""

    cascade_subdomain: Annotated[bool, pydantic.Field(alias="cascadeSubdomain")]
    r"""Cascade business units to domain's subdomains"""

    cascade_ip: Annotated[bool, pydantic.Field(alias="cascadeIp")]
    r"""Cascade business units to domain's ipaddresses"""
