"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .huntdetail import HuntDetail, HuntDetailTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class HuntDetailResponseTypedDict(TypedDict):
    data: HuntDetailTypedDict


class HuntDetailResponse(BaseModel):
    data: HuntDetail
