"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inviteuserresponse import InviteUserResponse, InviteUserResponseTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class InviteUserResponseDataTypedDict(TypedDict):
    data: InviteUserResponseTypedDict


class InviteUserResponseData(BaseModel):
    data: InviteUserResponse
