"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    QueryParamMetadata,
)


class ListSubmittedAssetsRequestTypedDict(TypedDict):
    page: NotRequired[float]
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""
    page_size: NotRequired[float]
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 20. The maximum for pageSize is 100."""
    business_unit_ids: NotRequired[str]
    r"""Filter by a list of comma separated business unit IDs that the seed data is related to."""


class ListSubmittedAssetsRequest(BaseModel):
    page: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results."""

    page_size: Annotated[
        Optional[float],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 20. The maximum for pageSize is 100."""

    business_unit_ids: Annotated[
        Optional[str],
        pydantic.Field(alias="businessUnitIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by a list of comma separated business unit IDs that the seed data is related to."""
