"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class MttrMetricsDtoTypedDict(TypedDict):
    mttr: float
    r"""Mean Time To Remediation in hours"""
    mttrae: float
    r"""Mean Time To Remediation After Exploitation in hours"""


class MttrMetricsDto(BaseModel):
    mttr: float
    r"""Mean Time To Remediation in hours"""

    mttrae: float
    r"""Mean Time To Remediation After Exploitation in hours"""
