"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientip import ClientIP, ClientIPTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientIPTypedDict(TypedDict):
    data: List[ClientIPTypedDict]
    meta: MetaTypedDict


class PaginatedClientIP(BaseModel):
    data: List[ClientIP]

    meta: Meta
