"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientpendingdomain import ClientPendingDomain, ClientPendingDomainTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientPendingDomainTypedDict(TypedDict):
    data: List[ClientPendingDomainTypedDict]
    r"""List of pending domain items"""
    meta: MetaTypedDict


class PaginatedClientPendingDomain(BaseModel):
    data: List[ClientPendingDomain]
    r"""List of pending domain items"""

    meta: Meta
