"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientdnsrecord import ClientDNSRecord, ClientDNSRecordTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientDNSRecordTypedDict(TypedDict):
    data: List[ClientDNSRecordTypedDict]
    r"""List of DNS record items"""
    meta: MetaTypedDict


class PaginatedClientDNSRecord(BaseModel):
    data: List[ClientDNSRecord]
    r"""List of DNS record items"""

    meta: Meta
