"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientiprange import ClientIPRange, ClientIPRangeTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientIPRangeTypedDict(TypedDict):
    data: List[ClientIPRangeTypedDict]
    meta: MetaTypedDict


class PaginatedClientIPRange(BaseModel):
    data: List[ClientIPRange]

    meta: Meta
