"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientcloudstorage import ClientCloudStorage, ClientCloudStorageTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientCloudStorageTypedDict(TypedDict):
    data: List[ClientCloudStorageTypedDict]
    meta: MetaTypedDict


class PaginatedClientCloudStorage(BaseModel):
    data: List[ClientCloudStorage]

    meta: Meta
