"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientfinding import ClientFinding, ClientFindingTypedDict
from .meta import Meta, MetaTypedDict
from typing import List
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class PaginatedClientFindingsTypedDict(TypedDict):
    data: List[ClientFindingTypedDict]
    meta: MetaTypedDict


class PaginatedClientFindings(BaseModel):
    data: List[ClientFinding]

    meta: Meta
