"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientbusinessunit import ClientBusinessUnit, ClientBusinessUnitTypedDict
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ServiceInformationAssetTypedDict(TypedDict):
    id: float
    r"""ID"""
    name: str
    r"""Asset name"""
    type: str
    r"""Asset type"""
    business_units: List[ClientBusinessUnitTypedDict]
    r"""Business Unit"""


class ServiceInformationAsset(BaseModel):
    id: float
    r"""ID"""

    name: str
    r"""Asset name"""

    type: str
    r"""Asset type"""

    business_units: Annotated[
        List[ClientBusinessUnit], pydantic.Field(alias="businessUnits")
    ]
    r"""Business Unit"""
