"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .serviceinformationasset import (
    ServiceInformationAsset,
    ServiceInformationAssetTypedDict,
)
from .serviceinformationcertificate import (
    ServiceInformationCertificate,
    ServiceInformationCertificateTypedDict,
)
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ServiceInformationResponseTypedDict(TypedDict):
    id: float
    r"""ID"""
    response: str
    r"""Response"""
    certificate: ServiceInformationCertificateTypedDict
    asset: ServiceInformationAssetTypedDict


class ServiceInformationResponse(BaseModel):
    id: float
    r"""ID"""

    response: str
    r"""Response"""

    certificate: ServiceInformationCertificate

    asset: ServiceInformationAsset
