"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientbusinessunit import ClientBusinessUnit, ClientBusinessUnitTypedDict
from .servicetype import ServiceType, ServiceTypeTypedDict
from .technology import Technology, TechnologyTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class ServiceListingTypedDict(TypedDict):
    id: float
    r"""ID"""
    port_id: float
    r"""Port ID"""
    ip: Nullable[str]
    r"""IP Address"""
    hostname: Nullable[str]
    r"""Hostname"""
    last_seen: datetime
    r"""Last seen date Range"""
    technologies: List[TechnologyTypedDict]
    r"""Technology list"""
    service_types: List[ServiceTypeTypedDict]
    r"""Service types"""
    business_units: List[ClientBusinessUnitTypedDict]
    r"""Business Units"""
    is_concerning: bool
    r"""Whether the discovered network service is concerning"""
    suppressed: bool
    r"""Whether the service is suppressed"""
    port: NotRequired[float]
    r"""Port number"""
    type: NotRequired[str]
    r"""Port Protocol"""
    country: NotRequired[str]
    r"""Country code"""
    banner: NotRequired[str]
    r"""Banner"""
    service: NotRequired[str]
    r"""Service"""
    source: NotRequired[str]
    r"""Asset source"""
    suppressed_at: NotRequired[Nullable[datetime]]
    r"""Suppressed at timestamp"""
    is_permanent_suppression: NotRequired[Nullable[bool]]
    r"""Whether the service is permanently suppressed"""


class ServiceListing(BaseModel):
    id: float
    r"""ID"""

    port_id: Annotated[float, pydantic.Field(alias="portId")]
    r"""Port ID"""

    ip: Nullable[str]
    r"""IP Address"""

    hostname: Nullable[str]
    r"""Hostname"""

    last_seen: Annotated[datetime, pydantic.Field(alias="lastSeen")]
    r"""Last seen date Range"""

    technologies: List[Technology]
    r"""Technology list"""

    service_types: Annotated[List[ServiceType], pydantic.Field(alias="serviceTypes")]
    r"""Service types"""

    business_units: Annotated[
        List[ClientBusinessUnit], pydantic.Field(alias="businessUnits")
    ]
    r"""Business Units"""

    is_concerning: Annotated[bool, pydantic.Field(alias="isConcerning")]
    r"""Whether the discovered network service is concerning"""

    suppressed: bool
    r"""Whether the service is suppressed"""

    port: Optional[float] = None
    r"""Port number"""

    type: Optional[str] = None
    r"""Port Protocol"""

    country: Optional[str] = None
    r"""Country code"""

    banner: Optional[str] = None
    r"""Banner"""

    service: Optional[str] = None
    r"""Service"""

    source: Optional[str] = None
    r"""Asset source"""

    suppressed_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="suppressedAt")
    ] = UNSET
    r"""Suppressed at timestamp"""

    is_permanent_suppression: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isPermanentSuppression")
    ] = UNSET
    r"""Whether the service is permanently suppressed"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "port",
            "type",
            "country",
            "banner",
            "service",
            "source",
            "suppressedAt",
            "isPermanentSuppression",
        ]
        nullable_fields = ["ip", "hostname", "suppressedAt", "isPermanentSuppression"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
