"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class ThreatActorDtoTypedDict(TypedDict):
    attacker_name: str
    r"""Threat actor name"""
    country: str
    r"""Country code"""


class ThreatActorDto(BaseModel):
    attacker_name: Annotated[str, pydantic.Field(alias="attackerName")]
    r"""Threat actor name"""

    country: str
    r"""Country code"""
