"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)


class UnassignSubomainFromBusinessUnitsRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of the subdomain to unassign."""
    business_unit_ids: List[str]
    r"""List of comma-seperated business unit IDs to unassign from the asset."""
    cascade_subdomain: str
    r"""Cascade business units to domain's subdomains"""
    cascade_ip: str
    r"""Cascade business units to domain's ipaddresses"""


class UnassignSubomainFromBusinessUnitsRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of the subdomain to unassign."""

    business_unit_ids: Annotated[
        List[str],
        pydantic.Field(alias="businessUnitIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""List of comma-seperated business unit IDs to unassign from the asset."""

    cascade_subdomain: Annotated[
        str,
        pydantic.Field(alias="cascadeSubdomain"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Cascade business units to domain's subdomains"""

    cascade_ip: Annotated[
        str,
        pydantic.Field(alias="cascadeIp"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Cascade business units to domain's ipaddresses"""
