"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated
from watchtowr_complete_watchtowr_platform_api_documentation_python import utils
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UnauthorizedData(BaseModel):
    message: str
    r"""Error message"""

    status_code: Annotated[float, pydantic.Field(alias="statusCode")]
    r"""HTTP status code"""


class Unauthorized(Exception):
    data: UnauthorizedData

    def __init__(self, data: UnauthorizedData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, UnauthorizedData)
