"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class UpdateClientBusinessUnitDtoType(str, Enum):
    r"""Business unit type"""

    BRAND = "BRAND"
    DEPARTMENT = "DEPARTMENT"
    LEGAL_ENTITY = "LEGAL_ENTITY"
    LEGAL_ENTITY_ORG_STRUCTURE = "LEGAL_ENTITY_ORG_STRUCTURE"
    M_A = "M_A"
    THIRD_PARTY = "THIRD_PARTY"
    USER_DEFINED = "USER_DEFINED"
    SYSTEM_FAVORITE_ASSET = "SYSTEM_FAVORITE_ASSET"


class UpdateClientBusinessUnitDtoTypedDict(TypedDict):
    name: str
    r"""Business unit name"""
    type: UpdateClientBusinessUnitDtoType
    r"""Business unit type"""
    description: NotRequired[str]
    r"""Business unit description"""
    parent_id: NotRequired[Nullable[float]]
    r"""Parent business unit ID. Set to null to remove parent relationship."""
    user_ids: NotRequired[List[float]]
    r"""Array of user IDs to assign to this business unit"""


class UpdateClientBusinessUnitDto(BaseModel):
    name: str
    r"""Business unit name"""

    type: UpdateClientBusinessUnitDtoType
    r"""Business unit type"""

    description: Optional[str] = None
    r"""Business unit description"""

    parent_id: OptionalNullable[float] = UNSET
    r"""Parent business unit ID. Set to null to remove parent relationship."""

    user_ids: Optional[List[float]] = None
    r"""Array of user IDs to assign to this business unit"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "parent_id", "user_ids"]
        nullable_fields = ["parent_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
