"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientfindingstaterequestbody import (
    UpdateClientFindingStateRequestBody,
    UpdateClientFindingStateRequestBodyTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateFindingStateRequestTypedDict(TypedDict):
    id: float
    r"""The ID of the finding to update."""
    update_client_finding_state_request_body: (
        UpdateClientFindingStateRequestBodyTypedDict
    )


class UpdateFindingStateRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the finding to update."""

    update_client_finding_state_request_body: Annotated[
        UpdateClientFindingStateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
