"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateKillSwitchResponseTypedDict(TypedDict):
    enabled: bool
    r"""Updated kill switch status"""
    message: str
    r"""Success message"""


class UpdateKillSwitchResponse(BaseModel):
    enabled: bool
    r"""Updated kill switch status"""

    message: str
    r"""Success message"""
