"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientcustompropertydto import (
    UpdateClientCustomPropertyDto,
    UpdateClientCustomPropertyDtoTypedDict,
)
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateCustomPropertyPackageManagerRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of a Package Manager asset with a custom property to update."""
    custom_property_id: float
    r"""The ID of the custom property to update."""
    update_client_custom_property_dto: UpdateClientCustomPropertyDtoTypedDict


class UpdateCustomPropertyPackageManagerRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of a Package Manager asset with a custom property to update."""

    custom_property_id: Annotated[
        float,
        pydantic.Field(alias="customPropertyId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the custom property to update."""

    update_client_custom_property_dto: Annotated[
        UpdateClientCustomPropertyDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
