"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientlegacyassetstatusdto import (
    UpdateClientLegacyAssetStatusDto,
    UpdateClientLegacyAssetStatusDtoTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateAssetIPRangeStatusRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of the IP Range to update status of."""
    update_client_legacy_asset_status_dto: UpdateClientLegacyAssetStatusDtoTypedDict


class UpdateAssetIPRangeStatusRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of the IP Range to update status of."""

    update_client_legacy_asset_status_dto: Annotated[
        UpdateClientLegacyAssetStatusDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
