"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientnextgenassetstatusdto import (
    UpdateClientNextGenAssetStatusDto,
    UpdateClientNextGenAssetStatusDtoTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateAssetRepositoryStatusRequestTypedDict(TypedDict):
    id: float
    r"""The asset ID of the Repository asset to update the status of."""
    update_client_next_gen_asset_status_dto: UpdateClientNextGenAssetStatusDtoTypedDict


class UpdateAssetRepositoryStatusRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The asset ID of the Repository asset to update the status of."""

    update_client_next_gen_asset_status_dto: Annotated[
        UpdateClientNextGenAssetStatusDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
