"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateClientLegacyAssetStatusDtoStatus(str, Enum):
    r"""Target status to update."""

    VERIFIED = "verified"
    VERIFIED_OUT_OF_SCOPE = "VerifiedOutOfScope"
    VERIFIED_REDUCED_ATTACK = "VerifiedReducedAttack"
    INCORRECT_IDENTIFICATION = "Incorrect Identification"


class UpdateClientLegacyAssetStatusDtoTypedDict(TypedDict):
    status: UpdateClientLegacyAssetStatusDtoStatus
    r"""Target status to update."""
    status_reason: NotRequired[str]
    r"""Reason for updating status."""


class UpdateClientLegacyAssetStatusDto(BaseModel):
    status: UpdateClientLegacyAssetStatusDtoStatus
    r"""Target status to update."""

    status_reason: Optional[str] = None
    r"""Reason for updating status."""
