"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatekillswitchresponse import (
    UpdateKillSwitchResponse,
    UpdateKillSwitchResponseTypedDict,
)
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateKillSwitchDataTypedDict(TypedDict):
    data: UpdateKillSwitchResponseTypedDict


class UpdateKillSwitchData(BaseModel):
    data: UpdateKillSwitchResponse
