"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientfindingstatusrequestbody import (
    UpdateClientFindingStatusRequestBody,
    UpdateClientFindingStatusRequestBodyTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateFindingStatusRequestTypedDict(TypedDict):
    id: float
    r"""The ID of the finding to update."""
    update_client_finding_status_request_body: (
        UpdateClientFindingStatusRequestBodyTypedDict
    )


class UpdateFindingStatusRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the finding to update."""

    update_client_finding_status_request_body: Annotated[
        UpdateClientFindingStatusRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
