"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateClientEngineSettingsDtoTypedDict(TypedDict):
    adversary_sight_enabled: bool
    r"""This setting manages the Adversary Sight engine coverage for the asset."""
    dns_bruteforcing_enabled: bool
    r"""This setting manages the DNS Bruteforcing engine coverage for the asset."""
    automated_red_teaming_enabled: bool
    r"""This setting manages the Automated Red Teaming engine coverage for the asset."""
    intrusive_http_checks_enabled: bool
    r"""This setting manages Intrusive HTTP Check engine coverage for the asset."""
    credential_stuffing_enabled: bool
    r"""This setting manages the Credential Stuffing engine coverage for the asset."""
    rapid_reaction_enabled: bool
    r"""This setting manages the Rapid Reaction engine coverage for the asset"""


class UpdateClientEngineSettingsDto(BaseModel):
    adversary_sight_enabled: Annotated[
        bool, pydantic.Field(alias="adversarySightEnabled")
    ]
    r"""This setting manages the Adversary Sight engine coverage for the asset."""

    dns_bruteforcing_enabled: Annotated[
        bool, pydantic.Field(alias="dnsBruteforcingEnabled")
    ]
    r"""This setting manages the DNS Bruteforcing engine coverage for the asset."""

    automated_red_teaming_enabled: Annotated[
        bool, pydantic.Field(alias="automatedRedTeamingEnabled")
    ]
    r"""This setting manages the Automated Red Teaming engine coverage for the asset."""

    intrusive_http_checks_enabled: Annotated[
        bool, pydantic.Field(alias="intrusiveHttpChecksEnabled")
    ]
    r"""This setting manages Intrusive HTTP Check engine coverage for the asset."""

    credential_stuffing_enabled: Annotated[
        bool, pydantic.Field(alias="credentialStuffingEnabled")
    ]
    r"""This setting manages the Credential Stuffing engine coverage for the asset."""

    rapid_reaction_enabled: Annotated[
        bool, pydantic.Field(alias="rapidReactionEnabled")
    ]
    r"""This setting manages the Rapid Reaction engine coverage for the asset"""
