"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientuserbodydto import (
    UpdateClientUserBodyDto,
    UpdateClientUserBodyDtoTypedDict,
)
import pydantic
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateUserRequestTypedDict(TypedDict):
    id: float
    user_agent: str
    update_client_user_body_dto: UpdateClientUserBodyDtoTypedDict


class UpdateUserRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    user_agent: Annotated[
        str,
        pydantic.Field(alias="User-Agent"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]

    update_client_user_body_dto: Annotated[
        UpdateClientUserBodyDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
