"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateclientbusinessunitdto import (
    UpdateClientBusinessUnitDto,
    UpdateClientBusinessUnitDtoTypedDict,
)
from typing_extensions import Annotated, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)


class UpdateBusinessUnitRequestTypedDict(TypedDict):
    id: float
    r"""The ID of the business unit to update."""
    update_client_business_unit_dto: UpdateClientBusinessUnitDtoTypedDict


class UpdateBusinessUnitRequest(BaseModel):
    id: Annotated[
        float, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the business unit to update."""

    update_client_business_unit_dto: Annotated[
        UpdateClientBusinessUnitDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
