"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateKillSwitchRequestDtoTypedDict(TypedDict):
    value: bool
    r"""Kill switch value (true to enable, false to disable)"""
    reason: NotRequired[str]
    r"""Reason for enabling the kill switch (required when enabling)"""
    request_support: NotRequired[bool]
    r"""Whether to request support from watchTowr (optional, defaults to false)"""


class UpdateKillSwitchRequestDto(BaseModel):
    value: bool
    r"""Kill switch value (true to enable, false to disable)"""

    reason: Optional[str] = None
    r"""Reason for enabling the kill switch (required when enabling)"""

    request_support: Annotated[
        Optional[bool], pydantic.Field(alias="requestSupport")
    ] = None
    r"""Whether to request support from watchTowr (optional, defaults to false)"""
