"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class UpdateClientFindingStatusRequestBodyTypedDict(TypedDict):
    status: str
    r"""Finding status."""
    status_reason: NotRequired[str]
    r"""Reason for the status change."""


class UpdateClientFindingStatusRequestBody(BaseModel):
    status: str
    r"""Finding status."""

    status_reason: Annotated[Optional[str], pydantic.Field(alias="statusReason")] = None
    r"""Reason for the status change."""
