"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .whitelistipdata import WhitelistIPData, WhitelistIPDataTypedDict
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class WhitelistIPDataSingleTypedDict(TypedDict):
    data: WhitelistIPDataTypedDict
    r"""Whitelisted IP details"""


class WhitelistIPDataSingle(BaseModel):
    data: WhitelistIPData
    r"""Whitelisted IP details"""
