"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    BaseModel,
)


class WhitelistStatusDataTypedDict(TypedDict):
    enabled: bool
    r"""Current whitelisting status"""


class WhitelistStatusData(BaseModel):
    enabled: bool
    r"""Current whitelisting status"""
