# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.latest_executed_hunt_dto import LatestExecutedHuntDto
from typing import Optional, Set
from typing_extensions import Self

class HuntOverviewDto(BaseModel):
    """
    HuntOverviewDto
    """ # noqa: E501
    total_hunts_executed: Union[StrictFloat, StrictInt] = Field(description="Total number of rapid reaction hunts executed", alias="totalHuntsExecuted")
    total_unresolved_hunts: Union[StrictFloat, StrictInt] = Field(description="Total number of unresolved hunts", alias="totalUnresolvedHunts")
    latest_executed_hunts: List[LatestExecutedHuntDto] = Field(description="Array of latest executed hunts", alias="latestExecutedHunts")
    __properties: ClassVar[List[str]] = ["totalHuntsExecuted", "totalUnresolvedHunts", "latestExecutedHunts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HuntOverviewDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in latest_executed_hunts (list)
        _items = []
        if self.latest_executed_hunts:
            for _item_latest_executed_hunts in self.latest_executed_hunts:
                if _item_latest_executed_hunts:
                    _items.append(_item_latest_executed_hunts.to_dict())
            _dict['latestExecutedHunts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HuntOverviewDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalHuntsExecuted": obj.get("totalHuntsExecuted"),
            "totalUnresolvedHunts": obj.get("totalUnresolvedHunts"),
            "latestExecutedHunts": [LatestExecutedHuntDto.from_dict(_item) for _item in obj["latestExecutedHunts"]] if obj.get("latestExecutedHunts") is not None else None
        })
        return _obj


