# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Continuous Assurance API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictFloat, StrictInt, StrictStr
from typing import List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.client_service_information_response_data import ClientServiceInformationResponseData
from openapi_client.models.paginated_service_information_response import PaginatedServiceInformationResponse

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class CertificatesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_certificate_details(
        self,
        id: Annotated[Union[StrictFloat, StrictInt], Field(description="The asset ID of the certificate to retrieve.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ClientServiceInformationResponseData:
        """Get Certificate Details

        Get the details of a specific TLS/SSL certificate.

        :param id: The asset ID of the certificate to retrieve. (required)
        :type id: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_certificate_details_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ClientServiceInformationResponseData",
            '401': "Unauthorized",
            '403': "ForbiddenResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_certificate_details_with_http_info(
        self,
        id: Annotated[Union[StrictFloat, StrictInt], Field(description="The asset ID of the certificate to retrieve.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ClientServiceInformationResponseData]:
        """Get Certificate Details

        Get the details of a specific TLS/SSL certificate.

        :param id: The asset ID of the certificate to retrieve. (required)
        :type id: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_certificate_details_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ClientServiceInformationResponseData",
            '401': "Unauthorized",
            '403': "ForbiddenResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_certificate_details_without_preload_content(
        self,
        id: Annotated[Union[StrictFloat, StrictInt], Field(description="The asset ID of the certificate to retrieve.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Certificate Details

        Get the details of a specific TLS/SSL certificate.

        :param id: The asset ID of the certificate to retrieve. (required)
        :type id: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_certificate_details_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ClientServiceInformationResponseData",
            '401': "Unauthorized",
            '403': "ForbiddenResponse",
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_certificate_details_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/client/certificates/show/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_list_certificates(
        self,
        page: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.")] = None,
        page_size: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Filter certificates created after a given date and time.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Filter certificates created before a given date and time.")] = None,
        updated_from: Annotated[Optional[datetime], Field(description="Filter certificates updated after a given date and time.")] = None,
        updated_to: Annotated[Optional[datetime], Field(description="Filter certificates updated before a given date and time.")] = None,
        not_after_from: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire after a given date and time.")] = None,
        not_after_to: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire before a given date and time.")] = None,
        subject_common_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Common Name.")] = None,
        subject_alt_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Alt Name.")] = None,
        subject_organisation_search: Annotated[Optional[StrictStr], Field(description="Search by subject organization.")] = None,
        subject_countries: Annotated[Optional[List[StrictStr]], Field(description="Filter certificates by a list of comma separated subject countries that they're related to.")] = None,
        asset_name_search: Annotated[Optional[StrictStr], Field(description="Search Certificates by the name of the associated asset.")] = None,
        statuses: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated statuses that they're tagged with.")] = None,
        business_unit_ids: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated business unit IDs they're related to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedServiceInformationResponse:
        """List Certificates

        List all discovered TLS/SSL certificate assets, ordered by discovery date.

        :param page: The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.
        :type page: float
        :param page_size: The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.
        :type page_size: float
        :param created_from: Filter certificates created after a given date and time.
        :type created_from: datetime
        :param created_to: Filter certificates created before a given date and time.
        :type created_to: datetime
        :param updated_from: Filter certificates updated after a given date and time.
        :type updated_from: datetime
        :param updated_to: Filter certificates updated before a given date and time.
        :type updated_to: datetime
        :param not_after_from: Filter certificates that do not expire after a given date and time.
        :type not_after_from: datetime
        :param not_after_to: Filter certificates that do not expire before a given date and time.
        :type not_after_to: datetime
        :param subject_common_name_search: Search certificates by Subject Common Name.
        :type subject_common_name_search: str
        :param subject_alt_name_search: Search certificates by Subject Alt Name.
        :type subject_alt_name_search: str
        :param subject_organisation_search: Search by subject organization.
        :type subject_organisation_search: str
        :param subject_countries: Filter certificates by a list of comma separated subject countries that they're related to.
        :type subject_countries: List[str]
        :param asset_name_search: Search Certificates by the name of the associated asset.
        :type asset_name_search: str
        :param statuses: Filter certificates by a list of comma separated statuses that they're tagged with.
        :type statuses: str
        :param business_unit_ids: Filter certificates by a list of comma separated business unit IDs they're related to.
        :type business_unit_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_list_certificates_serialize(
            page=page,
            page_size=page_size,
            created_from=created_from,
            created_to=created_to,
            updated_from=updated_from,
            updated_to=updated_to,
            not_after_from=not_after_from,
            not_after_to=not_after_to,
            subject_common_name_search=subject_common_name_search,
            subject_alt_name_search=subject_alt_name_search,
            subject_organisation_search=subject_organisation_search,
            subject_countries=subject_countries,
            asset_name_search=asset_name_search,
            statuses=statuses,
            business_unit_ids=business_unit_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedServiceInformationResponse",
            '401': "Unauthorized",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_list_certificates_with_http_info(
        self,
        page: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.")] = None,
        page_size: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Filter certificates created after a given date and time.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Filter certificates created before a given date and time.")] = None,
        updated_from: Annotated[Optional[datetime], Field(description="Filter certificates updated after a given date and time.")] = None,
        updated_to: Annotated[Optional[datetime], Field(description="Filter certificates updated before a given date and time.")] = None,
        not_after_from: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire after a given date and time.")] = None,
        not_after_to: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire before a given date and time.")] = None,
        subject_common_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Common Name.")] = None,
        subject_alt_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Alt Name.")] = None,
        subject_organisation_search: Annotated[Optional[StrictStr], Field(description="Search by subject organization.")] = None,
        subject_countries: Annotated[Optional[List[StrictStr]], Field(description="Filter certificates by a list of comma separated subject countries that they're related to.")] = None,
        asset_name_search: Annotated[Optional[StrictStr], Field(description="Search Certificates by the name of the associated asset.")] = None,
        statuses: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated statuses that they're tagged with.")] = None,
        business_unit_ids: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated business unit IDs they're related to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedServiceInformationResponse]:
        """List Certificates

        List all discovered TLS/SSL certificate assets, ordered by discovery date.

        :param page: The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.
        :type page: float
        :param page_size: The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.
        :type page_size: float
        :param created_from: Filter certificates created after a given date and time.
        :type created_from: datetime
        :param created_to: Filter certificates created before a given date and time.
        :type created_to: datetime
        :param updated_from: Filter certificates updated after a given date and time.
        :type updated_from: datetime
        :param updated_to: Filter certificates updated before a given date and time.
        :type updated_to: datetime
        :param not_after_from: Filter certificates that do not expire after a given date and time.
        :type not_after_from: datetime
        :param not_after_to: Filter certificates that do not expire before a given date and time.
        :type not_after_to: datetime
        :param subject_common_name_search: Search certificates by Subject Common Name.
        :type subject_common_name_search: str
        :param subject_alt_name_search: Search certificates by Subject Alt Name.
        :type subject_alt_name_search: str
        :param subject_organisation_search: Search by subject organization.
        :type subject_organisation_search: str
        :param subject_countries: Filter certificates by a list of comma separated subject countries that they're related to.
        :type subject_countries: List[str]
        :param asset_name_search: Search Certificates by the name of the associated asset.
        :type asset_name_search: str
        :param statuses: Filter certificates by a list of comma separated statuses that they're tagged with.
        :type statuses: str
        :param business_unit_ids: Filter certificates by a list of comma separated business unit IDs they're related to.
        :type business_unit_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_list_certificates_serialize(
            page=page,
            page_size=page_size,
            created_from=created_from,
            created_to=created_to,
            updated_from=updated_from,
            updated_to=updated_to,
            not_after_from=not_after_from,
            not_after_to=not_after_to,
            subject_common_name_search=subject_common_name_search,
            subject_alt_name_search=subject_alt_name_search,
            subject_organisation_search=subject_organisation_search,
            subject_countries=subject_countries,
            asset_name_search=asset_name_search,
            statuses=statuses,
            business_unit_ids=business_unit_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedServiceInformationResponse",
            '401': "Unauthorized",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_list_certificates_without_preload_content(
        self,
        page: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.")] = None,
        page_size: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.")] = None,
        created_from: Annotated[Optional[datetime], Field(description="Filter certificates created after a given date and time.")] = None,
        created_to: Annotated[Optional[datetime], Field(description="Filter certificates created before a given date and time.")] = None,
        updated_from: Annotated[Optional[datetime], Field(description="Filter certificates updated after a given date and time.")] = None,
        updated_to: Annotated[Optional[datetime], Field(description="Filter certificates updated before a given date and time.")] = None,
        not_after_from: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire after a given date and time.")] = None,
        not_after_to: Annotated[Optional[datetime], Field(description="Filter certificates that do not expire before a given date and time.")] = None,
        subject_common_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Common Name.")] = None,
        subject_alt_name_search: Annotated[Optional[StrictStr], Field(description="Search certificates by Subject Alt Name.")] = None,
        subject_organisation_search: Annotated[Optional[StrictStr], Field(description="Search by subject organization.")] = None,
        subject_countries: Annotated[Optional[List[StrictStr]], Field(description="Filter certificates by a list of comma separated subject countries that they're related to.")] = None,
        asset_name_search: Annotated[Optional[StrictStr], Field(description="Search Certificates by the name of the associated asset.")] = None,
        statuses: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated statuses that they're tagged with.")] = None,
        business_unit_ids: Annotated[Optional[StrictStr], Field(description="Filter certificates by a list of comma separated business unit IDs they're related to.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Certificates

        List all discovered TLS/SSL certificate assets, ordered by discovery date.

        :param page: The page number for paginated results. If the page field is not provided in the request, it defaults to 1, which corresponds to the first page of results.
        :type page: float
        :param page_size: The number of items to be included on each page of paginated results. If the pageSize field is not specified, it defaults to 10. The maximum for pageSize is 30.
        :type page_size: float
        :param created_from: Filter certificates created after a given date and time.
        :type created_from: datetime
        :param created_to: Filter certificates created before a given date and time.
        :type created_to: datetime
        :param updated_from: Filter certificates updated after a given date and time.
        :type updated_from: datetime
        :param updated_to: Filter certificates updated before a given date and time.
        :type updated_to: datetime
        :param not_after_from: Filter certificates that do not expire after a given date and time.
        :type not_after_from: datetime
        :param not_after_to: Filter certificates that do not expire before a given date and time.
        :type not_after_to: datetime
        :param subject_common_name_search: Search certificates by Subject Common Name.
        :type subject_common_name_search: str
        :param subject_alt_name_search: Search certificates by Subject Alt Name.
        :type subject_alt_name_search: str
        :param subject_organisation_search: Search by subject organization.
        :type subject_organisation_search: str
        :param subject_countries: Filter certificates by a list of comma separated subject countries that they're related to.
        :type subject_countries: List[str]
        :param asset_name_search: Search Certificates by the name of the associated asset.
        :type asset_name_search: str
        :param statuses: Filter certificates by a list of comma separated statuses that they're tagged with.
        :type statuses: str
        :param business_unit_ids: Filter certificates by a list of comma separated business unit IDs they're related to.
        :type business_unit_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_list_certificates_serialize(
            page=page,
            page_size=page_size,
            created_from=created_from,
            created_to=created_to,
            updated_from=updated_from,
            updated_to=updated_to,
            not_after_from=not_after_from,
            not_after_to=not_after_to,
            subject_common_name_search=subject_common_name_search,
            subject_alt_name_search=subject_alt_name_search,
            subject_organisation_search=subject_organisation_search,
            subject_countries=subject_countries,
            asset_name_search=asset_name_search,
            statuses=statuses,
            business_unit_ids=business_unit_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PaginatedServiceInformationResponse",
            '401': "Unauthorized",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_list_certificates_serialize(
        self,
        page,
        page_size,
        created_from,
        created_to,
        updated_from,
        updated_to,
        not_after_from,
        not_after_to,
        subject_common_name_search,
        subject_alt_name_search,
        subject_organisation_search,
        subject_countries,
        asset_name_search,
        statuses,
        business_unit_ids,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'subjectCountries': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if created_from is not None:
            if isinstance(created_from, datetime):
                _query_params.append(
                    (
                        'created_from',
                        created_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_from', created_from))
            
        if created_to is not None:
            if isinstance(created_to, datetime):
                _query_params.append(
                    (
                        'created_to',
                        created_to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_to', created_to))
            
        if updated_from is not None:
            if isinstance(updated_from, datetime):
                _query_params.append(
                    (
                        'updated_from',
                        updated_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_from', updated_from))
            
        if updated_to is not None:
            if isinstance(updated_to, datetime):
                _query_params.append(
                    (
                        'updated_to',
                        updated_to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_to', updated_to))
            
        if not_after_from is not None:
            if isinstance(not_after_from, datetime):
                _query_params.append(
                    (
                        'not_after_from',
                        not_after_from.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('not_after_from', not_after_from))
            
        if not_after_to is not None:
            if isinstance(not_after_to, datetime):
                _query_params.append(
                    (
                        'not_after_to',
                        not_after_to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('not_after_to', not_after_to))
            
        if subject_common_name_search is not None:
            
            _query_params.append(('subjectCommonNameSearch', subject_common_name_search))
            
        if subject_alt_name_search is not None:
            
            _query_params.append(('subjectAltNameSearch', subject_alt_name_search))
            
        if subject_organisation_search is not None:
            
            _query_params.append(('subjectOrganisationSearch', subject_organisation_search))
            
        if subject_countries is not None:
            
            _query_params.append(('subjectCountries', subject_countries))
            
        if asset_name_search is not None:
            
            _query_params.append(('assetNameSearch', asset_name_search))
            
        if statuses is not None:
            
            _query_params.append(('statuses', statuses))
            
        if business_unit_ids is not None:
            
            _query_params.append(('businessUnitIds', business_unit_ids))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/client/certificates/list',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


