# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Active Defense API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from watchtowr_api_sdk.models.active_defense_rule_kev_status import ActiveDefenseRuleKevStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ActiveDefenseRule(BaseModel):
    """
    ActiveDefenseRule
    """ # noqa: E501
    id: StrictFloat
    rule_name: StrictStr = Field(alias="ruleName")
    cve_id: Optional[StrictStr] = Field(default=None, alias="cveId")
    wt_id: Optional[StrictFloat] = Field(default=None, alias="wtId")
    type: Optional[StrictStr] = None
    kev_status: ActiveDefenseRuleKevStatus = Field(alias="kevStatus")
    zero_day: StrictBool = Field(alias="zeroDay")
    providers: List[StrictStr]
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "ruleName", "cveId", "wtId", "type", "kevStatus", "zeroDay", "providers", "createdAt", "updatedAt"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cve', 'wt']):
            raise ValueError("must be one of enum values ('cve', 'wt')")
        return value

    @field_validator('providers')
    def providers_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['cloudflare', 'aws_cfn', 'fastly', 'akamai_waf', 'google_cloud_armor', 'mod_security', 'microsoft_azure_waf']):
                raise ValueError("each list item must be one of ('cloudflare', 'aws_cfn', 'fastly', 'akamai_waf', 'google_cloud_armor', 'mod_security', 'microsoft_azure_waf')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveDefenseRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of kev_status
        if self.kev_status:
            _dict['kevStatus'] = self.kev_status.to_dict()
        # set to None if cve_id (nullable) is None
        # and model_fields_set contains the field
        if self.cve_id is None and "cve_id" in self.model_fields_set:
            _dict['cveId'] = None

        # set to None if wt_id (nullable) is None
        # and model_fields_set contains the field
        if self.wt_id is None and "wt_id" in self.model_fields_set:
            _dict['wtId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveDefenseRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ActiveDefenseRule) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ruleName": obj.get("ruleName"),
            "cveId": obj.get("cveId"),
            "wtId": obj.get("wtId"),
            "type": obj.get("type"),
            "kevStatus": ActiveDefenseRuleKevStatus.from_dict(obj["kevStatus"]) if obj.get("kevStatus") is not None else None,
            "zeroDay": obj.get("zeroDay"),
            "providers": obj.get("providers"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


