# coding: utf-8

"""
    Complete watchTowr Platform API Documentation

    The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:       * Automated Red Teaming API       * Adversary Sight API       * Intelligence API       * Platform API 

    The version of the OpenAPI document: 1.0
    Contact: support@watchTowr.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from watchtowr_api_sdk.models.ip_range_values import IpRangeValues
from typing import Optional, Set
from typing_extensions import Self

class ClientSeedData(BaseModel):
    """
    ClientSeedData
    """ # noqa: E501
    title: StrictStr = Field(description="Descriptive title for the new asset")
    type: StrictStr = Field(description="Asset Type for the new asset. Valid asset types are: [domain, subdomain, ip, ipRange, repository, cloudStorage, container, mobileApp, saasPlatform, apiDocumentation, packageManager]")
    value: StrictStr = Field(description="Value for the asset to be added.")
    values: Optional[IpRangeValues] = Field(default=None, description="Values object for ipRange asset type. Must contain both cidr and asn fields. Required when type is ipRange.")
    __properties: ClassVar[List[str]] = ["title", "type", "value", "values"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['domain', 'subdomain', 'ip', 'ipRange', 'repository', 'cloudStorage', 'container', 'mobileApp', 'saasPlatform', 'apiDocumentation', 'packageManager']):
            raise ValueError("must be one of enum values ('domain', 'subdomain', 'ip', 'ipRange', 'repository', 'cloudStorage', 'container', 'mobileApp', 'saasPlatform', 'apiDocumentation', 'packageManager')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClientSeedData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of values
        if self.values:
            _dict['values'] = self.values.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClientSeedData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ClientSeedData) in the input: " + _key)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "type": obj.get("type"),
            "value": obj.get("value"),
            "values": IpRangeValues.from_dict(obj["values"]) if obj.get("values") is not None else None
        })
        return _obj


