"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration, ServerRegion
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from typing import Any, Callable, Dict, List, Optional, TYPE_CHECKING, Union, cast
from watchtowr_complete_watchtowr_platform_api_documentation_python import models, utils
from watchtowr_complete_watchtowr_platform_api_documentation_python._hooks import (
    SDKHooks,
)
from watchtowr_complete_watchtowr_platform_api_documentation_python.types import (
    OptionalNullable,
    UNSET,
)
import weakref

if TYPE_CHECKING:
    from watchtowr_complete_watchtowr_platform_api_documentation_python.activity_log import (
        ActivityLog,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.add_asset import (
        AddAsset,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.api_documentation import (
        APIDocumentation,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.business_unit import (
        BusinessUnit,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.certificates import (
        Certificates,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.cloud_integration_assets import (
        CloudIntegrationAssets,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.cloud_storage import (
        CloudStorage,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.containers import (
        Containers,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.dns_record_analysis import (
        DNSRecordAnalysis,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.domains import (
        Domains,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.finding_retest_history import (
        FindingRetestHistory,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.findings import (
        Findings,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.hunts import (
        Hunts,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.ip_addresses import (
        IPAddresses,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.ip_ranges import (
        IPRanges,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.kill_switch import (
        KillSwitch,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.mobile_applications import (
        MobileApplications,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.package_managers import (
        PackageManagers,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.pending_domains import (
        PendingDomains,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.platform_whitelisting import (
        PlatformWhitelisting,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.points_of_interest_sdk import (
        PointsOfInterestSDK,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.ports import (
        Ports,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.repositories import (
        Repositories,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.saas_platforms import (
        SaaSPlatforms,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.security_posture_dashboard import (
        SecurityPostureDashboard,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.service_discovery import (
        ServiceDiscovery,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.source_ip_addresses import (
        SourceIPAddresses,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.subdomains import (
        Subdomains,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.suspicious_domains import (
        SuspiciousDomains,
    )
    from watchtowr_complete_watchtowr_platform_api_documentation_python.user_management import (
        UserManagement,
    )


class CompleteWatchtowrPlatformAPIDocumentation(BaseSDK):
    r"""Complete watchTowr Platform API Documentation: The watchTowr Client API combining all watchTowr Platform APIs into a single comprehensive reference, including:
    * Automated Red Teaming API
    * Adversary Sight API
    * Intelligence API
    * Platform API
    """

    findings: "Findings"
    cloud_storage: "CloudStorage"
    containers: "Containers"
    repositories: "Repositories"
    mobile_applications: "MobileApplications"
    saa_s_platforms: "SaaSPlatforms"
    domains: "Domains"
    subdomains: "Subdomains"
    ip_addresses: "IPAddresses"
    ip_ranges: "IPRanges"
    ports: "Ports"
    cloud_integration_assets: "CloudIntegrationAssets"
    package_managers: "PackageManagers"
    api_documentation: "APIDocumentation"
    source_ip_addresses: "SourceIPAddresses"
    add_asset: "AddAsset"
    service_discovery: "ServiceDiscovery"
    points_of_interest: "PointsOfInterestSDK"
    business_unit: "BusinessUnit"
    suspicious_domains: "SuspiciousDomains"
    certificates: "Certificates"
    hunts: "Hunts"
    activity_log: "ActivityLog"
    finding_retest_history: "FindingRetestHistory"
    dns_record_analysis: "DNSRecordAnalysis"
    pending_domains: "PendingDomains"
    kill_switch: "KillSwitch"
    security_posture_dashboard: "SecurityPostureDashboard"
    user_management: "UserManagement"
    platform_whitelisting: "PlatformWhitelisting"
    _sub_sdk_map = {
        "findings": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.findings",
            "Findings",
        ),
        "cloud_storage": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.cloud_storage",
            "CloudStorage",
        ),
        "containers": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.containers",
            "Containers",
        ),
        "repositories": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.repositories",
            "Repositories",
        ),
        "mobile_applications": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.mobile_applications",
            "MobileApplications",
        ),
        "saa_s_platforms": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.saas_platforms",
            "SaaSPlatforms",
        ),
        "domains": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.domains",
            "Domains",
        ),
        "subdomains": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.subdomains",
            "Subdomains",
        ),
        "ip_addresses": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.ip_addresses",
            "IPAddresses",
        ),
        "ip_ranges": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.ip_ranges",
            "IPRanges",
        ),
        "ports": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.ports",
            "Ports",
        ),
        "cloud_integration_assets": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.cloud_integration_assets",
            "CloudIntegrationAssets",
        ),
        "package_managers": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.package_managers",
            "PackageManagers",
        ),
        "api_documentation": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.api_documentation",
            "APIDocumentation",
        ),
        "source_ip_addresses": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.source_ip_addresses",
            "SourceIPAddresses",
        ),
        "add_asset": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.add_asset",
            "AddAsset",
        ),
        "service_discovery": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.service_discovery",
            "ServiceDiscovery",
        ),
        "points_of_interest": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.points_of_interest_sdk",
            "PointsOfInterestSDK",
        ),
        "business_unit": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.business_unit",
            "BusinessUnit",
        ),
        "suspicious_domains": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.suspicious_domains",
            "SuspiciousDomains",
        ),
        "certificates": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.certificates",
            "Certificates",
        ),
        "hunts": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.hunts",
            "Hunts",
        ),
        "activity_log": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.activity_log",
            "ActivityLog",
        ),
        "finding_retest_history": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.finding_retest_history",
            "FindingRetestHistory",
        ),
        "dns_record_analysis": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.dns_record_analysis",
            "DNSRecordAnalysis",
        ),
        "pending_domains": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.pending_domains",
            "PendingDomains",
        ),
        "kill_switch": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.kill_switch",
            "KillSwitch",
        ),
        "security_posture_dashboard": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.security_posture_dashboard",
            "SecurityPostureDashboard",
        ),
        "user_management": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.user_management",
            "UserManagement",
        ),
        "platform_whitelisting": (
            "watchtowr_complete_watchtowr_platform_api_documentation_python.platform_whitelisting",
            "PlatformWhitelisting",
        ),
    }

    def __init__(
        self,
        bearer: Union[str, Callable[[], str]],
        tenant_id: Optional[str] = None,
        region: Optional[ServerRegion] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param bearer: The bearer required for authentication
        :param tenant_id: Allows setting the tenant-id variable for url substitution
        :param region: Allows setting the region variable for url substitution
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client()
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient()
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if callable(bearer):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.Security(bearer=bearer())
        else:
            security = models.Security(bearer=bearer)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)
        server_defaults: List[Dict[str, str]] = [
            {
                "tenant-id": tenant_id or "your-tenant-id",
                "region": region or "sg",
            },
        ]

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                server_defaults=server_defaults,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = importlib.import_module(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
